// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/solver_parameters.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2fsolver_5fparameters_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2fsolver_5fparameters_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ortools_2fconstraint_5fsolver_2fsolver_5fparameters_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ortools_2fconstraint_5fsolver_2fsolver_5fparameters_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ortools_2fconstraint_5fsolver_2fsolver_5fparameters_2eproto;
namespace operations_research {
class ConstraintSolverParameters;
struct ConstraintSolverParametersDefaultTypeInternal;
extern ConstraintSolverParametersDefaultTypeInternal _ConstraintSolverParameters_default_instance_;
}  // namespace operations_research
PROTOBUF_NAMESPACE_OPEN
template<> ::operations_research::ConstraintSolverParameters* Arena::CreateMaybeMessage<::operations_research::ConstraintSolverParameters>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace operations_research {

enum ConstraintSolverParameters_TrailCompression : int {
  ConstraintSolverParameters_TrailCompression_NO_COMPRESSION = 0,
  ConstraintSolverParameters_TrailCompression_COMPRESS_WITH_ZLIB = 1,
  ConstraintSolverParameters_TrailCompression_ConstraintSolverParameters_TrailCompression_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ConstraintSolverParameters_TrailCompression_ConstraintSolverParameters_TrailCompression_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ConstraintSolverParameters_TrailCompression_IsValid(int value);
constexpr ConstraintSolverParameters_TrailCompression ConstraintSolverParameters_TrailCompression_TrailCompression_MIN = ConstraintSolverParameters_TrailCompression_NO_COMPRESSION;
constexpr ConstraintSolverParameters_TrailCompression ConstraintSolverParameters_TrailCompression_TrailCompression_MAX = ConstraintSolverParameters_TrailCompression_COMPRESS_WITH_ZLIB;
constexpr int ConstraintSolverParameters_TrailCompression_TrailCompression_ARRAYSIZE = ConstraintSolverParameters_TrailCompression_TrailCompression_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ConstraintSolverParameters_TrailCompression_descriptor();
template<typename T>
inline const std::string& ConstraintSolverParameters_TrailCompression_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ConstraintSolverParameters_TrailCompression>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ConstraintSolverParameters_TrailCompression_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ConstraintSolverParameters_TrailCompression_descriptor(), enum_t_value);
}
inline bool ConstraintSolverParameters_TrailCompression_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ConstraintSolverParameters_TrailCompression* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ConstraintSolverParameters_TrailCompression>(
    ConstraintSolverParameters_TrailCompression_descriptor(), name, value);
}
// ===================================================================

class ConstraintSolverParameters final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.ConstraintSolverParameters) */ {
 public:
  inline ConstraintSolverParameters() : ConstraintSolverParameters(nullptr) {}
  ~ConstraintSolverParameters() override;
  explicit PROTOBUF_CONSTEXPR ConstraintSolverParameters(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConstraintSolverParameters(const ConstraintSolverParameters& from);
  ConstraintSolverParameters(ConstraintSolverParameters&& from) noexcept
    : ConstraintSolverParameters() {
    *this = ::std::move(from);
  }

  inline ConstraintSolverParameters& operator=(const ConstraintSolverParameters& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConstraintSolverParameters& operator=(ConstraintSolverParameters&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConstraintSolverParameters& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConstraintSolverParameters* internal_default_instance() {
    return reinterpret_cast<const ConstraintSolverParameters*>(
               &_ConstraintSolverParameters_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ConstraintSolverParameters& a, ConstraintSolverParameters& b) {
    a.Swap(&b);
  }
  inline void Swap(ConstraintSolverParameters* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConstraintSolverParameters* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConstraintSolverParameters* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConstraintSolverParameters>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ConstraintSolverParameters& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ConstraintSolverParameters& from) {
    ConstraintSolverParameters::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConstraintSolverParameters* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.ConstraintSolverParameters";
  }
  protected:
  explicit ConstraintSolverParameters(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ConstraintSolverParameters_TrailCompression TrailCompression;
  static constexpr TrailCompression NO_COMPRESSION =
    ConstraintSolverParameters_TrailCompression_NO_COMPRESSION;
  static constexpr TrailCompression COMPRESS_WITH_ZLIB =
    ConstraintSolverParameters_TrailCompression_COMPRESS_WITH_ZLIB;
  static inline bool TrailCompression_IsValid(int value) {
    return ConstraintSolverParameters_TrailCompression_IsValid(value);
  }
  static constexpr TrailCompression TrailCompression_MIN =
    ConstraintSolverParameters_TrailCompression_TrailCompression_MIN;
  static constexpr TrailCompression TrailCompression_MAX =
    ConstraintSolverParameters_TrailCompression_TrailCompression_MAX;
  static constexpr int TrailCompression_ARRAYSIZE =
    ConstraintSolverParameters_TrailCompression_TrailCompression_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  TrailCompression_descriptor() {
    return ConstraintSolverParameters_TrailCompression_descriptor();
  }
  template<typename T>
  static inline const std::string& TrailCompression_Name(T enum_t_value) {
    static_assert(::std::is_same<T, TrailCompression>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function TrailCompression_Name.");
    return ConstraintSolverParameters_TrailCompression_Name(enum_t_value);
  }
  static inline bool TrailCompression_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      TrailCompression* value) {
    return ConstraintSolverParameters_TrailCompression_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kProfileFileFieldNumber = 8,
    kCompressTrailFieldNumber = 1,
    kTrailBlockSizeFieldNumber = 2,
    kArraySplitSizeFieldNumber = 3,
    kStoreNamesFieldNumber = 4,
    kNameCastVariablesFieldNumber = 5,
    kNameAllVariablesFieldNumber = 6,
    kProfilePropagationFieldNumber = 7,
    kPrintModelFieldNumber = 11,
    kPrintModelStatsFieldNumber = 12,
    kPrintAddedConstraintsFieldNumber = 13,
    kDisableSolveFieldNumber = 15,
    kProfileLocalSearchFieldNumber = 16,
    kPrintLocalSearchProfileFieldNumber = 17,
    kTracePropagationFieldNumber = 9,
    kTraceSearchFieldNumber = 10,
    kUseSmallTableFieldNumber = 101,
    kUseCumulativeEdgeFinderFieldNumber = 105,
    kUseCumulativeTimeTableFieldNumber = 106,
    kUseCumulativeTimeTableSyncFieldNumber = 112,
    kMaxEdgeFinderSizeFieldNumber = 109,
    kUseSequenceHighDemandTasksFieldNumber = 107,
    kUseAllPossibleDisjunctionsFieldNumber = 108,
    kDiffnUseCumulativeFieldNumber = 110,
    kUseElementRmqFieldNumber = 111,
    kSkipLocallyOptimalPathsFieldNumber = 113,
    kCheckSolutionPeriodFieldNumber = 114,
  };
  // string profile_file = 8;
  void clear_profile_file();
  const std::string& profile_file() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_profile_file(ArgT0&& arg0, ArgT... args);
  std::string* mutable_profile_file();
  PROTOBUF_NODISCARD std::string* release_profile_file();
  void set_allocated_profile_file(std::string* profile_file);
  private:
  const std::string& _internal_profile_file() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_profile_file(const std::string& value);
  std::string* _internal_mutable_profile_file();
  public:

  // .operations_research.ConstraintSolverParameters.TrailCompression compress_trail = 1;
  void clear_compress_trail();
  ::operations_research::ConstraintSolverParameters_TrailCompression compress_trail() const;
  void set_compress_trail(::operations_research::ConstraintSolverParameters_TrailCompression value);
  private:
  ::operations_research::ConstraintSolverParameters_TrailCompression _internal_compress_trail() const;
  void _internal_set_compress_trail(::operations_research::ConstraintSolverParameters_TrailCompression value);
  public:

  // int32 trail_block_size = 2;
  void clear_trail_block_size();
  int32_t trail_block_size() const;
  void set_trail_block_size(int32_t value);
  private:
  int32_t _internal_trail_block_size() const;
  void _internal_set_trail_block_size(int32_t value);
  public:

  // int32 array_split_size = 3;
  void clear_array_split_size();
  int32_t array_split_size() const;
  void set_array_split_size(int32_t value);
  private:
  int32_t _internal_array_split_size() const;
  void _internal_set_array_split_size(int32_t value);
  public:

  // bool store_names = 4;
  void clear_store_names();
  bool store_names() const;
  void set_store_names(bool value);
  private:
  bool _internal_store_names() const;
  void _internal_set_store_names(bool value);
  public:

  // bool name_cast_variables = 5;
  void clear_name_cast_variables();
  bool name_cast_variables() const;
  void set_name_cast_variables(bool value);
  private:
  bool _internal_name_cast_variables() const;
  void _internal_set_name_cast_variables(bool value);
  public:

  // bool name_all_variables = 6;
  void clear_name_all_variables();
  bool name_all_variables() const;
  void set_name_all_variables(bool value);
  private:
  bool _internal_name_all_variables() const;
  void _internal_set_name_all_variables(bool value);
  public:

  // bool profile_propagation = 7;
  void clear_profile_propagation();
  bool profile_propagation() const;
  void set_profile_propagation(bool value);
  private:
  bool _internal_profile_propagation() const;
  void _internal_set_profile_propagation(bool value);
  public:

  // bool print_model = 11;
  void clear_print_model();
  bool print_model() const;
  void set_print_model(bool value);
  private:
  bool _internal_print_model() const;
  void _internal_set_print_model(bool value);
  public:

  // bool print_model_stats = 12;
  void clear_print_model_stats();
  bool print_model_stats() const;
  void set_print_model_stats(bool value);
  private:
  bool _internal_print_model_stats() const;
  void _internal_set_print_model_stats(bool value);
  public:

  // bool print_added_constraints = 13;
  void clear_print_added_constraints();
  bool print_added_constraints() const;
  void set_print_added_constraints(bool value);
  private:
  bool _internal_print_added_constraints() const;
  void _internal_set_print_added_constraints(bool value);
  public:

  // bool disable_solve = 15;
  void clear_disable_solve();
  bool disable_solve() const;
  void set_disable_solve(bool value);
  private:
  bool _internal_disable_solve() const;
  void _internal_set_disable_solve(bool value);
  public:

  // bool profile_local_search = 16;
  void clear_profile_local_search();
  bool profile_local_search() const;
  void set_profile_local_search(bool value);
  private:
  bool _internal_profile_local_search() const;
  void _internal_set_profile_local_search(bool value);
  public:

  // bool print_local_search_profile = 17;
  void clear_print_local_search_profile();
  bool print_local_search_profile() const;
  void set_print_local_search_profile(bool value);
  private:
  bool _internal_print_local_search_profile() const;
  void _internal_set_print_local_search_profile(bool value);
  public:

  // bool trace_propagation = 9;
  void clear_trace_propagation();
  bool trace_propagation() const;
  void set_trace_propagation(bool value);
  private:
  bool _internal_trace_propagation() const;
  void _internal_set_trace_propagation(bool value);
  public:

  // bool trace_search = 10;
  void clear_trace_search();
  bool trace_search() const;
  void set_trace_search(bool value);
  private:
  bool _internal_trace_search() const;
  void _internal_set_trace_search(bool value);
  public:

  // bool use_small_table = 101;
  void clear_use_small_table();
  bool use_small_table() const;
  void set_use_small_table(bool value);
  private:
  bool _internal_use_small_table() const;
  void _internal_set_use_small_table(bool value);
  public:

  // bool use_cumulative_edge_finder = 105;
  void clear_use_cumulative_edge_finder();
  bool use_cumulative_edge_finder() const;
  void set_use_cumulative_edge_finder(bool value);
  private:
  bool _internal_use_cumulative_edge_finder() const;
  void _internal_set_use_cumulative_edge_finder(bool value);
  public:

  // bool use_cumulative_time_table = 106;
  void clear_use_cumulative_time_table();
  bool use_cumulative_time_table() const;
  void set_use_cumulative_time_table(bool value);
  private:
  bool _internal_use_cumulative_time_table() const;
  void _internal_set_use_cumulative_time_table(bool value);
  public:

  // bool use_cumulative_time_table_sync = 112;
  void clear_use_cumulative_time_table_sync();
  bool use_cumulative_time_table_sync() const;
  void set_use_cumulative_time_table_sync(bool value);
  private:
  bool _internal_use_cumulative_time_table_sync() const;
  void _internal_set_use_cumulative_time_table_sync(bool value);
  public:

  // int32 max_edge_finder_size = 109;
  void clear_max_edge_finder_size();
  int32_t max_edge_finder_size() const;
  void set_max_edge_finder_size(int32_t value);
  private:
  int32_t _internal_max_edge_finder_size() const;
  void _internal_set_max_edge_finder_size(int32_t value);
  public:

  // bool use_sequence_high_demand_tasks = 107;
  void clear_use_sequence_high_demand_tasks();
  bool use_sequence_high_demand_tasks() const;
  void set_use_sequence_high_demand_tasks(bool value);
  private:
  bool _internal_use_sequence_high_demand_tasks() const;
  void _internal_set_use_sequence_high_demand_tasks(bool value);
  public:

  // bool use_all_possible_disjunctions = 108;
  void clear_use_all_possible_disjunctions();
  bool use_all_possible_disjunctions() const;
  void set_use_all_possible_disjunctions(bool value);
  private:
  bool _internal_use_all_possible_disjunctions() const;
  void _internal_set_use_all_possible_disjunctions(bool value);
  public:

  // bool diffn_use_cumulative = 110;
  void clear_diffn_use_cumulative();
  bool diffn_use_cumulative() const;
  void set_diffn_use_cumulative(bool value);
  private:
  bool _internal_diffn_use_cumulative() const;
  void _internal_set_diffn_use_cumulative(bool value);
  public:

  // bool use_element_rmq = 111;
  void clear_use_element_rmq();
  bool use_element_rmq() const;
  void set_use_element_rmq(bool value);
  private:
  bool _internal_use_element_rmq() const;
  void _internal_set_use_element_rmq(bool value);
  public:

  // bool skip_locally_optimal_paths = 113;
  void clear_skip_locally_optimal_paths();
  bool skip_locally_optimal_paths() const;
  void set_skip_locally_optimal_paths(bool value);
  private:
  bool _internal_skip_locally_optimal_paths() const;
  void _internal_set_skip_locally_optimal_paths(bool value);
  public:

  // int32 check_solution_period = 114;
  void clear_check_solution_period();
  int32_t check_solution_period() const;
  void set_check_solution_period(int32_t value);
  private:
  int32_t _internal_check_solution_period() const;
  void _internal_set_check_solution_period(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:operations_research.ConstraintSolverParameters)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr profile_file_;
    int compress_trail_;
    int32_t trail_block_size_;
    int32_t array_split_size_;
    bool store_names_;
    bool name_cast_variables_;
    bool name_all_variables_;
    bool profile_propagation_;
    bool print_model_;
    bool print_model_stats_;
    bool print_added_constraints_;
    bool disable_solve_;
    bool profile_local_search_;
    bool print_local_search_profile_;
    bool trace_propagation_;
    bool trace_search_;
    bool use_small_table_;
    bool use_cumulative_edge_finder_;
    bool use_cumulative_time_table_;
    bool use_cumulative_time_table_sync_;
    int32_t max_edge_finder_size_;
    bool use_sequence_high_demand_tasks_;
    bool use_all_possible_disjunctions_;
    bool diffn_use_cumulative_;
    bool use_element_rmq_;
    bool skip_locally_optimal_paths_;
    int32_t check_solution_period_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fconstraint_5fsolver_2fsolver_5fparameters_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConstraintSolverParameters

// .operations_research.ConstraintSolverParameters.TrailCompression compress_trail = 1;
inline void ConstraintSolverParameters::clear_compress_trail() {
  _impl_.compress_trail_ = 0;
}
inline ::operations_research::ConstraintSolverParameters_TrailCompression ConstraintSolverParameters::_internal_compress_trail() const {
  return static_cast< ::operations_research::ConstraintSolverParameters_TrailCompression >(_impl_.compress_trail_);
}
inline ::operations_research::ConstraintSolverParameters_TrailCompression ConstraintSolverParameters::compress_trail() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.compress_trail)
  return _internal_compress_trail();
}
inline void ConstraintSolverParameters::_internal_set_compress_trail(::operations_research::ConstraintSolverParameters_TrailCompression value) {
  
  _impl_.compress_trail_ = value;
}
inline void ConstraintSolverParameters::set_compress_trail(::operations_research::ConstraintSolverParameters_TrailCompression value) {
  _internal_set_compress_trail(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.compress_trail)
}

// int32 trail_block_size = 2;
inline void ConstraintSolverParameters::clear_trail_block_size() {
  _impl_.trail_block_size_ = 0;
}
inline int32_t ConstraintSolverParameters::_internal_trail_block_size() const {
  return _impl_.trail_block_size_;
}
inline int32_t ConstraintSolverParameters::trail_block_size() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.trail_block_size)
  return _internal_trail_block_size();
}
inline void ConstraintSolverParameters::_internal_set_trail_block_size(int32_t value) {
  
  _impl_.trail_block_size_ = value;
}
inline void ConstraintSolverParameters::set_trail_block_size(int32_t value) {
  _internal_set_trail_block_size(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.trail_block_size)
}

// int32 array_split_size = 3;
inline void ConstraintSolverParameters::clear_array_split_size() {
  _impl_.array_split_size_ = 0;
}
inline int32_t ConstraintSolverParameters::_internal_array_split_size() const {
  return _impl_.array_split_size_;
}
inline int32_t ConstraintSolverParameters::array_split_size() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.array_split_size)
  return _internal_array_split_size();
}
inline void ConstraintSolverParameters::_internal_set_array_split_size(int32_t value) {
  
  _impl_.array_split_size_ = value;
}
inline void ConstraintSolverParameters::set_array_split_size(int32_t value) {
  _internal_set_array_split_size(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.array_split_size)
}

// bool store_names = 4;
inline void ConstraintSolverParameters::clear_store_names() {
  _impl_.store_names_ = false;
}
inline bool ConstraintSolverParameters::_internal_store_names() const {
  return _impl_.store_names_;
}
inline bool ConstraintSolverParameters::store_names() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.store_names)
  return _internal_store_names();
}
inline void ConstraintSolverParameters::_internal_set_store_names(bool value) {
  
  _impl_.store_names_ = value;
}
inline void ConstraintSolverParameters::set_store_names(bool value) {
  _internal_set_store_names(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.store_names)
}

// bool name_cast_variables = 5;
inline void ConstraintSolverParameters::clear_name_cast_variables() {
  _impl_.name_cast_variables_ = false;
}
inline bool ConstraintSolverParameters::_internal_name_cast_variables() const {
  return _impl_.name_cast_variables_;
}
inline bool ConstraintSolverParameters::name_cast_variables() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.name_cast_variables)
  return _internal_name_cast_variables();
}
inline void ConstraintSolverParameters::_internal_set_name_cast_variables(bool value) {
  
  _impl_.name_cast_variables_ = value;
}
inline void ConstraintSolverParameters::set_name_cast_variables(bool value) {
  _internal_set_name_cast_variables(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.name_cast_variables)
}

// bool name_all_variables = 6;
inline void ConstraintSolverParameters::clear_name_all_variables() {
  _impl_.name_all_variables_ = false;
}
inline bool ConstraintSolverParameters::_internal_name_all_variables() const {
  return _impl_.name_all_variables_;
}
inline bool ConstraintSolverParameters::name_all_variables() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.name_all_variables)
  return _internal_name_all_variables();
}
inline void ConstraintSolverParameters::_internal_set_name_all_variables(bool value) {
  
  _impl_.name_all_variables_ = value;
}
inline void ConstraintSolverParameters::set_name_all_variables(bool value) {
  _internal_set_name_all_variables(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.name_all_variables)
}

// bool profile_propagation = 7;
inline void ConstraintSolverParameters::clear_profile_propagation() {
  _impl_.profile_propagation_ = false;
}
inline bool ConstraintSolverParameters::_internal_profile_propagation() const {
  return _impl_.profile_propagation_;
}
inline bool ConstraintSolverParameters::profile_propagation() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.profile_propagation)
  return _internal_profile_propagation();
}
inline void ConstraintSolverParameters::_internal_set_profile_propagation(bool value) {
  
  _impl_.profile_propagation_ = value;
}
inline void ConstraintSolverParameters::set_profile_propagation(bool value) {
  _internal_set_profile_propagation(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.profile_propagation)
}

// string profile_file = 8;
inline void ConstraintSolverParameters::clear_profile_file() {
  _impl_.profile_file_.ClearToEmpty();
}
inline const std::string& ConstraintSolverParameters::profile_file() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.profile_file)
  return _internal_profile_file();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ConstraintSolverParameters::set_profile_file(ArgT0&& arg0, ArgT... args) {
 
 _impl_.profile_file_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.profile_file)
}
inline std::string* ConstraintSolverParameters::mutable_profile_file() {
  std::string* _s = _internal_mutable_profile_file();
  // @@protoc_insertion_point(field_mutable:operations_research.ConstraintSolverParameters.profile_file)
  return _s;
}
inline const std::string& ConstraintSolverParameters::_internal_profile_file() const {
  return _impl_.profile_file_.Get();
}
inline void ConstraintSolverParameters::_internal_set_profile_file(const std::string& value) {
  
  _impl_.profile_file_.Set(value, GetArenaForAllocation());
}
inline std::string* ConstraintSolverParameters::_internal_mutable_profile_file() {
  
  return _impl_.profile_file_.Mutable(GetArenaForAllocation());
}
inline std::string* ConstraintSolverParameters::release_profile_file() {
  // @@protoc_insertion_point(field_release:operations_research.ConstraintSolverParameters.profile_file)
  return _impl_.profile_file_.Release();
}
inline void ConstraintSolverParameters::set_allocated_profile_file(std::string* profile_file) {
  if (profile_file != nullptr) {
    
  } else {
    
  }
  _impl_.profile_file_.SetAllocated(profile_file, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.profile_file_.IsDefault()) {
    _impl_.profile_file_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:operations_research.ConstraintSolverParameters.profile_file)
}

// bool profile_local_search = 16;
inline void ConstraintSolverParameters::clear_profile_local_search() {
  _impl_.profile_local_search_ = false;
}
inline bool ConstraintSolverParameters::_internal_profile_local_search() const {
  return _impl_.profile_local_search_;
}
inline bool ConstraintSolverParameters::profile_local_search() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.profile_local_search)
  return _internal_profile_local_search();
}
inline void ConstraintSolverParameters::_internal_set_profile_local_search(bool value) {
  
  _impl_.profile_local_search_ = value;
}
inline void ConstraintSolverParameters::set_profile_local_search(bool value) {
  _internal_set_profile_local_search(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.profile_local_search)
}

// bool print_local_search_profile = 17;
inline void ConstraintSolverParameters::clear_print_local_search_profile() {
  _impl_.print_local_search_profile_ = false;
}
inline bool ConstraintSolverParameters::_internal_print_local_search_profile() const {
  return _impl_.print_local_search_profile_;
}
inline bool ConstraintSolverParameters::print_local_search_profile() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.print_local_search_profile)
  return _internal_print_local_search_profile();
}
inline void ConstraintSolverParameters::_internal_set_print_local_search_profile(bool value) {
  
  _impl_.print_local_search_profile_ = value;
}
inline void ConstraintSolverParameters::set_print_local_search_profile(bool value) {
  _internal_set_print_local_search_profile(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.print_local_search_profile)
}

// bool trace_propagation = 9;
inline void ConstraintSolverParameters::clear_trace_propagation() {
  _impl_.trace_propagation_ = false;
}
inline bool ConstraintSolverParameters::_internal_trace_propagation() const {
  return _impl_.trace_propagation_;
}
inline bool ConstraintSolverParameters::trace_propagation() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.trace_propagation)
  return _internal_trace_propagation();
}
inline void ConstraintSolverParameters::_internal_set_trace_propagation(bool value) {
  
  _impl_.trace_propagation_ = value;
}
inline void ConstraintSolverParameters::set_trace_propagation(bool value) {
  _internal_set_trace_propagation(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.trace_propagation)
}

// bool trace_search = 10;
inline void ConstraintSolverParameters::clear_trace_search() {
  _impl_.trace_search_ = false;
}
inline bool ConstraintSolverParameters::_internal_trace_search() const {
  return _impl_.trace_search_;
}
inline bool ConstraintSolverParameters::trace_search() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.trace_search)
  return _internal_trace_search();
}
inline void ConstraintSolverParameters::_internal_set_trace_search(bool value) {
  
  _impl_.trace_search_ = value;
}
inline void ConstraintSolverParameters::set_trace_search(bool value) {
  _internal_set_trace_search(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.trace_search)
}

// bool print_model = 11;
inline void ConstraintSolverParameters::clear_print_model() {
  _impl_.print_model_ = false;
}
inline bool ConstraintSolverParameters::_internal_print_model() const {
  return _impl_.print_model_;
}
inline bool ConstraintSolverParameters::print_model() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.print_model)
  return _internal_print_model();
}
inline void ConstraintSolverParameters::_internal_set_print_model(bool value) {
  
  _impl_.print_model_ = value;
}
inline void ConstraintSolverParameters::set_print_model(bool value) {
  _internal_set_print_model(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.print_model)
}

// bool print_model_stats = 12;
inline void ConstraintSolverParameters::clear_print_model_stats() {
  _impl_.print_model_stats_ = false;
}
inline bool ConstraintSolverParameters::_internal_print_model_stats() const {
  return _impl_.print_model_stats_;
}
inline bool ConstraintSolverParameters::print_model_stats() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.print_model_stats)
  return _internal_print_model_stats();
}
inline void ConstraintSolverParameters::_internal_set_print_model_stats(bool value) {
  
  _impl_.print_model_stats_ = value;
}
inline void ConstraintSolverParameters::set_print_model_stats(bool value) {
  _internal_set_print_model_stats(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.print_model_stats)
}

// bool print_added_constraints = 13;
inline void ConstraintSolverParameters::clear_print_added_constraints() {
  _impl_.print_added_constraints_ = false;
}
inline bool ConstraintSolverParameters::_internal_print_added_constraints() const {
  return _impl_.print_added_constraints_;
}
inline bool ConstraintSolverParameters::print_added_constraints() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.print_added_constraints)
  return _internal_print_added_constraints();
}
inline void ConstraintSolverParameters::_internal_set_print_added_constraints(bool value) {
  
  _impl_.print_added_constraints_ = value;
}
inline void ConstraintSolverParameters::set_print_added_constraints(bool value) {
  _internal_set_print_added_constraints(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.print_added_constraints)
}

// bool disable_solve = 15;
inline void ConstraintSolverParameters::clear_disable_solve() {
  _impl_.disable_solve_ = false;
}
inline bool ConstraintSolverParameters::_internal_disable_solve() const {
  return _impl_.disable_solve_;
}
inline bool ConstraintSolverParameters::disable_solve() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.disable_solve)
  return _internal_disable_solve();
}
inline void ConstraintSolverParameters::_internal_set_disable_solve(bool value) {
  
  _impl_.disable_solve_ = value;
}
inline void ConstraintSolverParameters::set_disable_solve(bool value) {
  _internal_set_disable_solve(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.disable_solve)
}

// bool use_small_table = 101;
inline void ConstraintSolverParameters::clear_use_small_table() {
  _impl_.use_small_table_ = false;
}
inline bool ConstraintSolverParameters::_internal_use_small_table() const {
  return _impl_.use_small_table_;
}
inline bool ConstraintSolverParameters::use_small_table() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.use_small_table)
  return _internal_use_small_table();
}
inline void ConstraintSolverParameters::_internal_set_use_small_table(bool value) {
  
  _impl_.use_small_table_ = value;
}
inline void ConstraintSolverParameters::set_use_small_table(bool value) {
  _internal_set_use_small_table(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.use_small_table)
}

// bool use_cumulative_edge_finder = 105;
inline void ConstraintSolverParameters::clear_use_cumulative_edge_finder() {
  _impl_.use_cumulative_edge_finder_ = false;
}
inline bool ConstraintSolverParameters::_internal_use_cumulative_edge_finder() const {
  return _impl_.use_cumulative_edge_finder_;
}
inline bool ConstraintSolverParameters::use_cumulative_edge_finder() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.use_cumulative_edge_finder)
  return _internal_use_cumulative_edge_finder();
}
inline void ConstraintSolverParameters::_internal_set_use_cumulative_edge_finder(bool value) {
  
  _impl_.use_cumulative_edge_finder_ = value;
}
inline void ConstraintSolverParameters::set_use_cumulative_edge_finder(bool value) {
  _internal_set_use_cumulative_edge_finder(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.use_cumulative_edge_finder)
}

// bool use_cumulative_time_table = 106;
inline void ConstraintSolverParameters::clear_use_cumulative_time_table() {
  _impl_.use_cumulative_time_table_ = false;
}
inline bool ConstraintSolverParameters::_internal_use_cumulative_time_table() const {
  return _impl_.use_cumulative_time_table_;
}
inline bool ConstraintSolverParameters::use_cumulative_time_table() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.use_cumulative_time_table)
  return _internal_use_cumulative_time_table();
}
inline void ConstraintSolverParameters::_internal_set_use_cumulative_time_table(bool value) {
  
  _impl_.use_cumulative_time_table_ = value;
}
inline void ConstraintSolverParameters::set_use_cumulative_time_table(bool value) {
  _internal_set_use_cumulative_time_table(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.use_cumulative_time_table)
}

// bool use_cumulative_time_table_sync = 112;
inline void ConstraintSolverParameters::clear_use_cumulative_time_table_sync() {
  _impl_.use_cumulative_time_table_sync_ = false;
}
inline bool ConstraintSolverParameters::_internal_use_cumulative_time_table_sync() const {
  return _impl_.use_cumulative_time_table_sync_;
}
inline bool ConstraintSolverParameters::use_cumulative_time_table_sync() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.use_cumulative_time_table_sync)
  return _internal_use_cumulative_time_table_sync();
}
inline void ConstraintSolverParameters::_internal_set_use_cumulative_time_table_sync(bool value) {
  
  _impl_.use_cumulative_time_table_sync_ = value;
}
inline void ConstraintSolverParameters::set_use_cumulative_time_table_sync(bool value) {
  _internal_set_use_cumulative_time_table_sync(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.use_cumulative_time_table_sync)
}

// bool use_sequence_high_demand_tasks = 107;
inline void ConstraintSolverParameters::clear_use_sequence_high_demand_tasks() {
  _impl_.use_sequence_high_demand_tasks_ = false;
}
inline bool ConstraintSolverParameters::_internal_use_sequence_high_demand_tasks() const {
  return _impl_.use_sequence_high_demand_tasks_;
}
inline bool ConstraintSolverParameters::use_sequence_high_demand_tasks() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.use_sequence_high_demand_tasks)
  return _internal_use_sequence_high_demand_tasks();
}
inline void ConstraintSolverParameters::_internal_set_use_sequence_high_demand_tasks(bool value) {
  
  _impl_.use_sequence_high_demand_tasks_ = value;
}
inline void ConstraintSolverParameters::set_use_sequence_high_demand_tasks(bool value) {
  _internal_set_use_sequence_high_demand_tasks(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.use_sequence_high_demand_tasks)
}

// bool use_all_possible_disjunctions = 108;
inline void ConstraintSolverParameters::clear_use_all_possible_disjunctions() {
  _impl_.use_all_possible_disjunctions_ = false;
}
inline bool ConstraintSolverParameters::_internal_use_all_possible_disjunctions() const {
  return _impl_.use_all_possible_disjunctions_;
}
inline bool ConstraintSolverParameters::use_all_possible_disjunctions() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.use_all_possible_disjunctions)
  return _internal_use_all_possible_disjunctions();
}
inline void ConstraintSolverParameters::_internal_set_use_all_possible_disjunctions(bool value) {
  
  _impl_.use_all_possible_disjunctions_ = value;
}
inline void ConstraintSolverParameters::set_use_all_possible_disjunctions(bool value) {
  _internal_set_use_all_possible_disjunctions(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.use_all_possible_disjunctions)
}

// int32 max_edge_finder_size = 109;
inline void ConstraintSolverParameters::clear_max_edge_finder_size() {
  _impl_.max_edge_finder_size_ = 0;
}
inline int32_t ConstraintSolverParameters::_internal_max_edge_finder_size() const {
  return _impl_.max_edge_finder_size_;
}
inline int32_t ConstraintSolverParameters::max_edge_finder_size() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.max_edge_finder_size)
  return _internal_max_edge_finder_size();
}
inline void ConstraintSolverParameters::_internal_set_max_edge_finder_size(int32_t value) {
  
  _impl_.max_edge_finder_size_ = value;
}
inline void ConstraintSolverParameters::set_max_edge_finder_size(int32_t value) {
  _internal_set_max_edge_finder_size(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.max_edge_finder_size)
}

// bool diffn_use_cumulative = 110;
inline void ConstraintSolverParameters::clear_diffn_use_cumulative() {
  _impl_.diffn_use_cumulative_ = false;
}
inline bool ConstraintSolverParameters::_internal_diffn_use_cumulative() const {
  return _impl_.diffn_use_cumulative_;
}
inline bool ConstraintSolverParameters::diffn_use_cumulative() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.diffn_use_cumulative)
  return _internal_diffn_use_cumulative();
}
inline void ConstraintSolverParameters::_internal_set_diffn_use_cumulative(bool value) {
  
  _impl_.diffn_use_cumulative_ = value;
}
inline void ConstraintSolverParameters::set_diffn_use_cumulative(bool value) {
  _internal_set_diffn_use_cumulative(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.diffn_use_cumulative)
}

// bool use_element_rmq = 111;
inline void ConstraintSolverParameters::clear_use_element_rmq() {
  _impl_.use_element_rmq_ = false;
}
inline bool ConstraintSolverParameters::_internal_use_element_rmq() const {
  return _impl_.use_element_rmq_;
}
inline bool ConstraintSolverParameters::use_element_rmq() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.use_element_rmq)
  return _internal_use_element_rmq();
}
inline void ConstraintSolverParameters::_internal_set_use_element_rmq(bool value) {
  
  _impl_.use_element_rmq_ = value;
}
inline void ConstraintSolverParameters::set_use_element_rmq(bool value) {
  _internal_set_use_element_rmq(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.use_element_rmq)
}

// bool skip_locally_optimal_paths = 113;
inline void ConstraintSolverParameters::clear_skip_locally_optimal_paths() {
  _impl_.skip_locally_optimal_paths_ = false;
}
inline bool ConstraintSolverParameters::_internal_skip_locally_optimal_paths() const {
  return _impl_.skip_locally_optimal_paths_;
}
inline bool ConstraintSolverParameters::skip_locally_optimal_paths() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.skip_locally_optimal_paths)
  return _internal_skip_locally_optimal_paths();
}
inline void ConstraintSolverParameters::_internal_set_skip_locally_optimal_paths(bool value) {
  
  _impl_.skip_locally_optimal_paths_ = value;
}
inline void ConstraintSolverParameters::set_skip_locally_optimal_paths(bool value) {
  _internal_set_skip_locally_optimal_paths(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.skip_locally_optimal_paths)
}

// int32 check_solution_period = 114;
inline void ConstraintSolverParameters::clear_check_solution_period() {
  _impl_.check_solution_period_ = 0;
}
inline int32_t ConstraintSolverParameters::_internal_check_solution_period() const {
  return _impl_.check_solution_period_;
}
inline int32_t ConstraintSolverParameters::check_solution_period() const {
  // @@protoc_insertion_point(field_get:operations_research.ConstraintSolverParameters.check_solution_period)
  return _internal_check_solution_period();
}
inline void ConstraintSolverParameters::_internal_set_check_solution_period(int32_t value) {
  
  _impl_.check_solution_period_ = value;
}
inline void ConstraintSolverParameters::set_check_solution_period(int32_t value) {
  _internal_set_check_solution_period(value);
  // @@protoc_insertion_point(field_set:operations_research.ConstraintSolverParameters.check_solution_period)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace operations_research

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::operations_research::ConstraintSolverParameters_TrailCompression> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::operations_research::ConstraintSolverParameters_TrailCompression>() {
  return ::operations_research::ConstraintSolverParameters_TrailCompression_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2fsolver_5fparameters_2eproto
