// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/sat/boolean_problem.proto

#ifndef PROTOBUF_INCLUDED_ortools_2fsat_2fboolean_5fproblem_2eproto
#define PROTOBUF_INCLUDED_ortools_2fsat_2fboolean_5fproblem_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ortools_2fsat_2fboolean_5fproblem_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ortools_2fsat_2fboolean_5fproblem_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ortools_2fsat_2fboolean_5fproblem_2eproto();
namespace operations_research {
class BooleanAssignment;
class BooleanAssignmentDefaultTypeInternal;
extern BooleanAssignmentDefaultTypeInternal _BooleanAssignment_default_instance_;
class LinearBooleanConstraint;
class LinearBooleanConstraintDefaultTypeInternal;
extern LinearBooleanConstraintDefaultTypeInternal _LinearBooleanConstraint_default_instance_;
class LinearBooleanProblem;
class LinearBooleanProblemDefaultTypeInternal;
extern LinearBooleanProblemDefaultTypeInternal _LinearBooleanProblem_default_instance_;
class LinearObjective;
class LinearObjectiveDefaultTypeInternal;
extern LinearObjectiveDefaultTypeInternal _LinearObjective_default_instance_;
}  // namespace operations_research
namespace google {
namespace protobuf {
template<> ::operations_research::BooleanAssignment* Arena::CreateMaybeMessage<::operations_research::BooleanAssignment>(Arena*);
template<> ::operations_research::LinearBooleanConstraint* Arena::CreateMaybeMessage<::operations_research::LinearBooleanConstraint>(Arena*);
template<> ::operations_research::LinearBooleanProblem* Arena::CreateMaybeMessage<::operations_research::LinearBooleanProblem>(Arena*);
template<> ::operations_research::LinearObjective* Arena::CreateMaybeMessage<::operations_research::LinearObjective>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace operations_research {

// ===================================================================

class LinearBooleanConstraint :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.LinearBooleanConstraint) */ {
 public:
  LinearBooleanConstraint();
  virtual ~LinearBooleanConstraint();

  LinearBooleanConstraint(const LinearBooleanConstraint& from);

  inline LinearBooleanConstraint& operator=(const LinearBooleanConstraint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LinearBooleanConstraint(LinearBooleanConstraint&& from) noexcept
    : LinearBooleanConstraint() {
    *this = ::std::move(from);
  }

  inline LinearBooleanConstraint& operator=(LinearBooleanConstraint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LinearBooleanConstraint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LinearBooleanConstraint* internal_default_instance() {
    return reinterpret_cast<const LinearBooleanConstraint*>(
               &_LinearBooleanConstraint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(LinearBooleanConstraint* other);
  friend void swap(LinearBooleanConstraint& a, LinearBooleanConstraint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LinearBooleanConstraint* New() const final {
    return CreateMaybeMessage<LinearBooleanConstraint>(nullptr);
  }

  LinearBooleanConstraint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LinearBooleanConstraint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LinearBooleanConstraint& from);
  void MergeFrom(const LinearBooleanConstraint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LinearBooleanConstraint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 literals = 1;
  int literals_size() const;
  void clear_literals();
  static const int kLiteralsFieldNumber = 1;
  ::google::protobuf::int32 literals(int index) const;
  void set_literals(int index, ::google::protobuf::int32 value);
  void add_literals(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      literals() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_literals();

  // repeated int64 coefficients = 2;
  int coefficients_size() const;
  void clear_coefficients();
  static const int kCoefficientsFieldNumber = 2;
  ::google::protobuf::int64 coefficients(int index) const;
  void set_coefficients(int index, ::google::protobuf::int64 value);
  void add_coefficients(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      coefficients() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_coefficients();

  // optional string name = 5 [default = ""];
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 5;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int64 lower_bound = 3;
  bool has_lower_bound() const;
  void clear_lower_bound();
  static const int kLowerBoundFieldNumber = 3;
  ::google::protobuf::int64 lower_bound() const;
  void set_lower_bound(::google::protobuf::int64 value);

  // optional int64 upper_bound = 4;
  bool has_upper_bound() const;
  void clear_upper_bound();
  static const int kUpperBoundFieldNumber = 4;
  ::google::protobuf::int64 upper_bound() const;
  void set_upper_bound(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:operations_research.LinearBooleanConstraint)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > literals_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > coefficients_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int64 lower_bound_;
  ::google::protobuf::int64 upper_bound_;
  friend struct ::TableStruct_ortools_2fsat_2fboolean_5fproblem_2eproto;
};
// -------------------------------------------------------------------

class LinearObjective :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.LinearObjective) */ {
 public:
  LinearObjective();
  virtual ~LinearObjective();

  LinearObjective(const LinearObjective& from);

  inline LinearObjective& operator=(const LinearObjective& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LinearObjective(LinearObjective&& from) noexcept
    : LinearObjective() {
    *this = ::std::move(from);
  }

  inline LinearObjective& operator=(LinearObjective&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LinearObjective& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LinearObjective* internal_default_instance() {
    return reinterpret_cast<const LinearObjective*>(
               &_LinearObjective_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(LinearObjective* other);
  friend void swap(LinearObjective& a, LinearObjective& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LinearObjective* New() const final {
    return CreateMaybeMessage<LinearObjective>(nullptr);
  }

  LinearObjective* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LinearObjective>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LinearObjective& from);
  void MergeFrom(const LinearObjective& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LinearObjective* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 literals = 1;
  int literals_size() const;
  void clear_literals();
  static const int kLiteralsFieldNumber = 1;
  ::google::protobuf::int32 literals(int index) const;
  void set_literals(int index, ::google::protobuf::int32 value);
  void add_literals(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      literals() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_literals();

  // repeated int64 coefficients = 2;
  int coefficients_size() const;
  void clear_coefficients();
  static const int kCoefficientsFieldNumber = 2;
  ::google::protobuf::int64 coefficients(int index) const;
  void set_coefficients(int index, ::google::protobuf::int64 value);
  void add_coefficients(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      coefficients() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_coefficients();

  // optional double offset = 3 [default = 0];
  bool has_offset() const;
  void clear_offset();
  static const int kOffsetFieldNumber = 3;
  double offset() const;
  void set_offset(double value);

  // optional double scaling_factor = 4 [default = 1];
  bool has_scaling_factor() const;
  void clear_scaling_factor();
  static const int kScalingFactorFieldNumber = 4;
  double scaling_factor() const;
  void set_scaling_factor(double value);

  // @@protoc_insertion_point(class_scope:operations_research.LinearObjective)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > literals_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > coefficients_;
  double offset_;
  double scaling_factor_;
  friend struct ::TableStruct_ortools_2fsat_2fboolean_5fproblem_2eproto;
};
// -------------------------------------------------------------------

class BooleanAssignment :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.BooleanAssignment) */ {
 public:
  BooleanAssignment();
  virtual ~BooleanAssignment();

  BooleanAssignment(const BooleanAssignment& from);

  inline BooleanAssignment& operator=(const BooleanAssignment& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BooleanAssignment(BooleanAssignment&& from) noexcept
    : BooleanAssignment() {
    *this = ::std::move(from);
  }

  inline BooleanAssignment& operator=(BooleanAssignment&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const BooleanAssignment& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BooleanAssignment* internal_default_instance() {
    return reinterpret_cast<const BooleanAssignment*>(
               &_BooleanAssignment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(BooleanAssignment* other);
  friend void swap(BooleanAssignment& a, BooleanAssignment& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BooleanAssignment* New() const final {
    return CreateMaybeMessage<BooleanAssignment>(nullptr);
  }

  BooleanAssignment* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BooleanAssignment>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BooleanAssignment& from);
  void MergeFrom(const BooleanAssignment& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BooleanAssignment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 literals = 1;
  int literals_size() const;
  void clear_literals();
  static const int kLiteralsFieldNumber = 1;
  ::google::protobuf::int32 literals(int index) const;
  void set_literals(int index, ::google::protobuf::int32 value);
  void add_literals(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      literals() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_literals();

  // @@protoc_insertion_point(class_scope:operations_research.BooleanAssignment)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > literals_;
  friend struct ::TableStruct_ortools_2fsat_2fboolean_5fproblem_2eproto;
};
// -------------------------------------------------------------------

class LinearBooleanProblem :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.LinearBooleanProblem) */ {
 public:
  LinearBooleanProblem();
  virtual ~LinearBooleanProblem();

  LinearBooleanProblem(const LinearBooleanProblem& from);

  inline LinearBooleanProblem& operator=(const LinearBooleanProblem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LinearBooleanProblem(LinearBooleanProblem&& from) noexcept
    : LinearBooleanProblem() {
    *this = ::std::move(from);
  }

  inline LinearBooleanProblem& operator=(LinearBooleanProblem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const LinearBooleanProblem& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LinearBooleanProblem* internal_default_instance() {
    return reinterpret_cast<const LinearBooleanProblem*>(
               &_LinearBooleanProblem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(LinearBooleanProblem* other);
  friend void swap(LinearBooleanProblem& a, LinearBooleanProblem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LinearBooleanProblem* New() const final {
    return CreateMaybeMessage<LinearBooleanProblem>(nullptr);
  }

  LinearBooleanProblem* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LinearBooleanProblem>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LinearBooleanProblem& from);
  void MergeFrom(const LinearBooleanProblem& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LinearBooleanProblem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .operations_research.LinearBooleanConstraint constraints = 4;
  int constraints_size() const;
  void clear_constraints();
  static const int kConstraintsFieldNumber = 4;
  ::operations_research::LinearBooleanConstraint* mutable_constraints(int index);
  ::google::protobuf::RepeatedPtrField< ::operations_research::LinearBooleanConstraint >*
      mutable_constraints();
  const ::operations_research::LinearBooleanConstraint& constraints(int index) const;
  ::operations_research::LinearBooleanConstraint* add_constraints();
  const ::google::protobuf::RepeatedPtrField< ::operations_research::LinearBooleanConstraint >&
      constraints() const;

  // repeated string var_names = 6;
  int var_names_size() const;
  void clear_var_names();
  static const int kVarNamesFieldNumber = 6;
  const ::std::string& var_names(int index) const;
  ::std::string* mutable_var_names(int index);
  void set_var_names(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_var_names(int index, ::std::string&& value);
  #endif
  void set_var_names(int index, const char* value);
  void set_var_names(int index, const char* value, size_t size);
  ::std::string* add_var_names();
  void add_var_names(const ::std::string& value);
  #if LANG_CXX11
  void add_var_names(::std::string&& value);
  #endif
  void add_var_names(const char* value);
  void add_var_names(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& var_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_var_names();

  // optional string name = 1 [default = ""];
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .operations_research.LinearObjective objective = 5;
  bool has_objective() const;
  void clear_objective();
  static const int kObjectiveFieldNumber = 5;
  const ::operations_research::LinearObjective& objective() const;
  ::operations_research::LinearObjective* release_objective();
  ::operations_research::LinearObjective* mutable_objective();
  void set_allocated_objective(::operations_research::LinearObjective* objective);

  // optional .operations_research.BooleanAssignment assignment = 7;
  bool has_assignment() const;
  void clear_assignment();
  static const int kAssignmentFieldNumber = 7;
  const ::operations_research::BooleanAssignment& assignment() const;
  ::operations_research::BooleanAssignment* release_assignment();
  ::operations_research::BooleanAssignment* mutable_assignment();
  void set_allocated_assignment(::operations_research::BooleanAssignment* assignment);

  // optional int32 num_variables = 3;
  bool has_num_variables() const;
  void clear_num_variables();
  static const int kNumVariablesFieldNumber = 3;
  ::google::protobuf::int32 num_variables() const;
  void set_num_variables(::google::protobuf::int32 value);

  // optional int32 original_num_variables = 8;
  bool has_original_num_variables() const;
  void clear_original_num_variables();
  static const int kOriginalNumVariablesFieldNumber = 8;
  ::google::protobuf::int32 original_num_variables() const;
  void set_original_num_variables(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:operations_research.LinearBooleanProblem)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::operations_research::LinearBooleanConstraint > constraints_;
  ::google::protobuf::RepeatedPtrField<::std::string> var_names_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::operations_research::LinearObjective* objective_;
  ::operations_research::BooleanAssignment* assignment_;
  ::google::protobuf::int32 num_variables_;
  ::google::protobuf::int32 original_num_variables_;
  friend struct ::TableStruct_ortools_2fsat_2fboolean_5fproblem_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LinearBooleanConstraint

// repeated int32 literals = 1;
inline int LinearBooleanConstraint::literals_size() const {
  return literals_.size();
}
inline void LinearBooleanConstraint::clear_literals() {
  literals_.Clear();
}
inline ::google::protobuf::int32 LinearBooleanConstraint::literals(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanConstraint.literals)
  return literals_.Get(index);
}
inline void LinearBooleanConstraint::set_literals(int index, ::google::protobuf::int32 value) {
  literals_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanConstraint.literals)
}
inline void LinearBooleanConstraint::add_literals(::google::protobuf::int32 value) {
  literals_.Add(value);
  // @@protoc_insertion_point(field_add:operations_research.LinearBooleanConstraint.literals)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
LinearBooleanConstraint::literals() const {
  // @@protoc_insertion_point(field_list:operations_research.LinearBooleanConstraint.literals)
  return literals_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
LinearBooleanConstraint::mutable_literals() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.LinearBooleanConstraint.literals)
  return &literals_;
}

// repeated int64 coefficients = 2;
inline int LinearBooleanConstraint::coefficients_size() const {
  return coefficients_.size();
}
inline void LinearBooleanConstraint::clear_coefficients() {
  coefficients_.Clear();
}
inline ::google::protobuf::int64 LinearBooleanConstraint::coefficients(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanConstraint.coefficients)
  return coefficients_.Get(index);
}
inline void LinearBooleanConstraint::set_coefficients(int index, ::google::protobuf::int64 value) {
  coefficients_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanConstraint.coefficients)
}
inline void LinearBooleanConstraint::add_coefficients(::google::protobuf::int64 value) {
  coefficients_.Add(value);
  // @@protoc_insertion_point(field_add:operations_research.LinearBooleanConstraint.coefficients)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
LinearBooleanConstraint::coefficients() const {
  // @@protoc_insertion_point(field_list:operations_research.LinearBooleanConstraint.coefficients)
  return coefficients_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
LinearBooleanConstraint::mutable_coefficients() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.LinearBooleanConstraint.coefficients)
  return &coefficients_;
}

// optional int64 lower_bound = 3;
inline bool LinearBooleanConstraint::has_lower_bound() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LinearBooleanConstraint::clear_lower_bound() {
  lower_bound_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 LinearBooleanConstraint::lower_bound() const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanConstraint.lower_bound)
  return lower_bound_;
}
inline void LinearBooleanConstraint::set_lower_bound(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  lower_bound_ = value;
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanConstraint.lower_bound)
}

// optional int64 upper_bound = 4;
inline bool LinearBooleanConstraint::has_upper_bound() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LinearBooleanConstraint::clear_upper_bound() {
  upper_bound_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 LinearBooleanConstraint::upper_bound() const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanConstraint.upper_bound)
  return upper_bound_;
}
inline void LinearBooleanConstraint::set_upper_bound(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  upper_bound_ = value;
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanConstraint.upper_bound)
}

// optional string name = 5 [default = ""];
inline bool LinearBooleanConstraint::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LinearBooleanConstraint::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& LinearBooleanConstraint::name() const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanConstraint.name)
  return name_.GetNoArena();
}
inline void LinearBooleanConstraint::set_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanConstraint.name)
}
#if LANG_CXX11
inline void LinearBooleanConstraint::set_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:operations_research.LinearBooleanConstraint.name)
}
#endif
inline void LinearBooleanConstraint::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:operations_research.LinearBooleanConstraint.name)
}
inline void LinearBooleanConstraint::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:operations_research.LinearBooleanConstraint.name)
}
inline ::std::string* LinearBooleanConstraint::mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:operations_research.LinearBooleanConstraint.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LinearBooleanConstraint::release_name() {
  // @@protoc_insertion_point(field_release:operations_research.LinearBooleanConstraint.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LinearBooleanConstraint::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:operations_research.LinearBooleanConstraint.name)
}

// -------------------------------------------------------------------

// LinearObjective

// repeated int32 literals = 1;
inline int LinearObjective::literals_size() const {
  return literals_.size();
}
inline void LinearObjective::clear_literals() {
  literals_.Clear();
}
inline ::google::protobuf::int32 LinearObjective::literals(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.LinearObjective.literals)
  return literals_.Get(index);
}
inline void LinearObjective::set_literals(int index, ::google::protobuf::int32 value) {
  literals_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.LinearObjective.literals)
}
inline void LinearObjective::add_literals(::google::protobuf::int32 value) {
  literals_.Add(value);
  // @@protoc_insertion_point(field_add:operations_research.LinearObjective.literals)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
LinearObjective::literals() const {
  // @@protoc_insertion_point(field_list:operations_research.LinearObjective.literals)
  return literals_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
LinearObjective::mutable_literals() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.LinearObjective.literals)
  return &literals_;
}

// repeated int64 coefficients = 2;
inline int LinearObjective::coefficients_size() const {
  return coefficients_.size();
}
inline void LinearObjective::clear_coefficients() {
  coefficients_.Clear();
}
inline ::google::protobuf::int64 LinearObjective::coefficients(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.LinearObjective.coefficients)
  return coefficients_.Get(index);
}
inline void LinearObjective::set_coefficients(int index, ::google::protobuf::int64 value) {
  coefficients_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.LinearObjective.coefficients)
}
inline void LinearObjective::add_coefficients(::google::protobuf::int64 value) {
  coefficients_.Add(value);
  // @@protoc_insertion_point(field_add:operations_research.LinearObjective.coefficients)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
LinearObjective::coefficients() const {
  // @@protoc_insertion_point(field_list:operations_research.LinearObjective.coefficients)
  return coefficients_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
LinearObjective::mutable_coefficients() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.LinearObjective.coefficients)
  return &coefficients_;
}

// optional double offset = 3 [default = 0];
inline bool LinearObjective::has_offset() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LinearObjective::clear_offset() {
  offset_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double LinearObjective::offset() const {
  // @@protoc_insertion_point(field_get:operations_research.LinearObjective.offset)
  return offset_;
}
inline void LinearObjective::set_offset(double value) {
  _has_bits_[0] |= 0x00000001u;
  offset_ = value;
  // @@protoc_insertion_point(field_set:operations_research.LinearObjective.offset)
}

// optional double scaling_factor = 4 [default = 1];
inline bool LinearObjective::has_scaling_factor() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LinearObjective::clear_scaling_factor() {
  scaling_factor_ = 1;
  _has_bits_[0] &= ~0x00000002u;
}
inline double LinearObjective::scaling_factor() const {
  // @@protoc_insertion_point(field_get:operations_research.LinearObjective.scaling_factor)
  return scaling_factor_;
}
inline void LinearObjective::set_scaling_factor(double value) {
  _has_bits_[0] |= 0x00000002u;
  scaling_factor_ = value;
  // @@protoc_insertion_point(field_set:operations_research.LinearObjective.scaling_factor)
}

// -------------------------------------------------------------------

// BooleanAssignment

// repeated int32 literals = 1;
inline int BooleanAssignment::literals_size() const {
  return literals_.size();
}
inline void BooleanAssignment::clear_literals() {
  literals_.Clear();
}
inline ::google::protobuf::int32 BooleanAssignment::literals(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.BooleanAssignment.literals)
  return literals_.Get(index);
}
inline void BooleanAssignment::set_literals(int index, ::google::protobuf::int32 value) {
  literals_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.BooleanAssignment.literals)
}
inline void BooleanAssignment::add_literals(::google::protobuf::int32 value) {
  literals_.Add(value);
  // @@protoc_insertion_point(field_add:operations_research.BooleanAssignment.literals)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
BooleanAssignment::literals() const {
  // @@protoc_insertion_point(field_list:operations_research.BooleanAssignment.literals)
  return literals_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
BooleanAssignment::mutable_literals() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.BooleanAssignment.literals)
  return &literals_;
}

// -------------------------------------------------------------------

// LinearBooleanProblem

// optional string name = 1 [default = ""];
inline bool LinearBooleanProblem::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LinearBooleanProblem::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& LinearBooleanProblem::name() const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanProblem.name)
  return name_.GetNoArena();
}
inline void LinearBooleanProblem::set_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanProblem.name)
}
#if LANG_CXX11
inline void LinearBooleanProblem::set_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:operations_research.LinearBooleanProblem.name)
}
#endif
inline void LinearBooleanProblem::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:operations_research.LinearBooleanProblem.name)
}
inline void LinearBooleanProblem::set_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:operations_research.LinearBooleanProblem.name)
}
inline ::std::string* LinearBooleanProblem::mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:operations_research.LinearBooleanProblem.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LinearBooleanProblem::release_name() {
  // @@protoc_insertion_point(field_release:operations_research.LinearBooleanProblem.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LinearBooleanProblem::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:operations_research.LinearBooleanProblem.name)
}

// optional int32 num_variables = 3;
inline bool LinearBooleanProblem::has_num_variables() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LinearBooleanProblem::clear_num_variables() {
  num_variables_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 LinearBooleanProblem::num_variables() const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanProblem.num_variables)
  return num_variables_;
}
inline void LinearBooleanProblem::set_num_variables(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  num_variables_ = value;
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanProblem.num_variables)
}

// repeated .operations_research.LinearBooleanConstraint constraints = 4;
inline int LinearBooleanProblem::constraints_size() const {
  return constraints_.size();
}
inline void LinearBooleanProblem::clear_constraints() {
  constraints_.Clear();
}
inline ::operations_research::LinearBooleanConstraint* LinearBooleanProblem::mutable_constraints(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.LinearBooleanProblem.constraints)
  return constraints_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::operations_research::LinearBooleanConstraint >*
LinearBooleanProblem::mutable_constraints() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.LinearBooleanProblem.constraints)
  return &constraints_;
}
inline const ::operations_research::LinearBooleanConstraint& LinearBooleanProblem::constraints(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanProblem.constraints)
  return constraints_.Get(index);
}
inline ::operations_research::LinearBooleanConstraint* LinearBooleanProblem::add_constraints() {
  // @@protoc_insertion_point(field_add:operations_research.LinearBooleanProblem.constraints)
  return constraints_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::operations_research::LinearBooleanConstraint >&
LinearBooleanProblem::constraints() const {
  // @@protoc_insertion_point(field_list:operations_research.LinearBooleanProblem.constraints)
  return constraints_;
}

// optional .operations_research.LinearObjective objective = 5;
inline bool LinearBooleanProblem::has_objective() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LinearBooleanProblem::clear_objective() {
  if (objective_ != nullptr) objective_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::operations_research::LinearObjective& LinearBooleanProblem::objective() const {
  const ::operations_research::LinearObjective* p = objective_;
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanProblem.objective)
  return p != nullptr ? *p : *reinterpret_cast<const ::operations_research::LinearObjective*>(
      &::operations_research::_LinearObjective_default_instance_);
}
inline ::operations_research::LinearObjective* LinearBooleanProblem::release_objective() {
  // @@protoc_insertion_point(field_release:operations_research.LinearBooleanProblem.objective)
  _has_bits_[0] &= ~0x00000002u;
  ::operations_research::LinearObjective* temp = objective_;
  objective_ = nullptr;
  return temp;
}
inline ::operations_research::LinearObjective* LinearBooleanProblem::mutable_objective() {
  _has_bits_[0] |= 0x00000002u;
  if (objective_ == nullptr) {
    auto* p = CreateMaybeMessage<::operations_research::LinearObjective>(GetArenaNoVirtual());
    objective_ = p;
  }
  // @@protoc_insertion_point(field_mutable:operations_research.LinearBooleanProblem.objective)
  return objective_;
}
inline void LinearBooleanProblem::set_allocated_objective(::operations_research::LinearObjective* objective) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete objective_;
  }
  if (objective) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      objective = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, objective, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  objective_ = objective;
  // @@protoc_insertion_point(field_set_allocated:operations_research.LinearBooleanProblem.objective)
}

// repeated string var_names = 6;
inline int LinearBooleanProblem::var_names_size() const {
  return var_names_.size();
}
inline void LinearBooleanProblem::clear_var_names() {
  var_names_.Clear();
}
inline const ::std::string& LinearBooleanProblem::var_names(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanProblem.var_names)
  return var_names_.Get(index);
}
inline ::std::string* LinearBooleanProblem::mutable_var_names(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.LinearBooleanProblem.var_names)
  return var_names_.Mutable(index);
}
inline void LinearBooleanProblem::set_var_names(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanProblem.var_names)
  var_names_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void LinearBooleanProblem::set_var_names(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanProblem.var_names)
  var_names_.Mutable(index)->assign(std::move(value));
}
#endif
inline void LinearBooleanProblem::set_var_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  var_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:operations_research.LinearBooleanProblem.var_names)
}
inline void LinearBooleanProblem::set_var_names(int index, const char* value, size_t size) {
  var_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:operations_research.LinearBooleanProblem.var_names)
}
inline ::std::string* LinearBooleanProblem::add_var_names() {
  // @@protoc_insertion_point(field_add_mutable:operations_research.LinearBooleanProblem.var_names)
  return var_names_.Add();
}
inline void LinearBooleanProblem::add_var_names(const ::std::string& value) {
  var_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:operations_research.LinearBooleanProblem.var_names)
}
#if LANG_CXX11
inline void LinearBooleanProblem::add_var_names(::std::string&& value) {
  var_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:operations_research.LinearBooleanProblem.var_names)
}
#endif
inline void LinearBooleanProblem::add_var_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  var_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:operations_research.LinearBooleanProblem.var_names)
}
inline void LinearBooleanProblem::add_var_names(const char* value, size_t size) {
  var_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:operations_research.LinearBooleanProblem.var_names)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
LinearBooleanProblem::var_names() const {
  // @@protoc_insertion_point(field_list:operations_research.LinearBooleanProblem.var_names)
  return var_names_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
LinearBooleanProblem::mutable_var_names() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.LinearBooleanProblem.var_names)
  return &var_names_;
}

// optional .operations_research.BooleanAssignment assignment = 7;
inline bool LinearBooleanProblem::has_assignment() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LinearBooleanProblem::clear_assignment() {
  if (assignment_ != nullptr) assignment_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::operations_research::BooleanAssignment& LinearBooleanProblem::assignment() const {
  const ::operations_research::BooleanAssignment* p = assignment_;
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanProblem.assignment)
  return p != nullptr ? *p : *reinterpret_cast<const ::operations_research::BooleanAssignment*>(
      &::operations_research::_BooleanAssignment_default_instance_);
}
inline ::operations_research::BooleanAssignment* LinearBooleanProblem::release_assignment() {
  // @@protoc_insertion_point(field_release:operations_research.LinearBooleanProblem.assignment)
  _has_bits_[0] &= ~0x00000004u;
  ::operations_research::BooleanAssignment* temp = assignment_;
  assignment_ = nullptr;
  return temp;
}
inline ::operations_research::BooleanAssignment* LinearBooleanProblem::mutable_assignment() {
  _has_bits_[0] |= 0x00000004u;
  if (assignment_ == nullptr) {
    auto* p = CreateMaybeMessage<::operations_research::BooleanAssignment>(GetArenaNoVirtual());
    assignment_ = p;
  }
  // @@protoc_insertion_point(field_mutable:operations_research.LinearBooleanProblem.assignment)
  return assignment_;
}
inline void LinearBooleanProblem::set_allocated_assignment(::operations_research::BooleanAssignment* assignment) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete assignment_;
  }
  if (assignment) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      assignment = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, assignment, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  assignment_ = assignment;
  // @@protoc_insertion_point(field_set_allocated:operations_research.LinearBooleanProblem.assignment)
}

// optional int32 original_num_variables = 8;
inline bool LinearBooleanProblem::has_original_num_variables() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LinearBooleanProblem::clear_original_num_variables() {
  original_num_variables_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::int32 LinearBooleanProblem::original_num_variables() const {
  // @@protoc_insertion_point(field_get:operations_research.LinearBooleanProblem.original_num_variables)
  return original_num_variables_;
}
inline void LinearBooleanProblem::set_original_num_variables(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  original_num_variables_ = value;
  // @@protoc_insertion_point(field_set:operations_research.LinearBooleanProblem.original_num_variables)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace operations_research

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ortools_2fsat_2fboolean_5fproblem_2eproto
