#ifndef __CONFIG_COINUTILS_H__
#define __CONFIG_COINUTILS_H__

#define COINUTILS_HAS_CSTDINT 1

/* COINUTILS_VERSION */
#define COINUTILS_VERSION "2.11.6"
/* COINUTILS_VERSION_MAJOR */
#define COINUTILS_VERSION_MAJOR 2
/* COINUTILS_VERSION_MINOR */
#define COINUTILS_VERSION_MINOR 11
/* COINUTILS_VERSION_RELEASE */
#define COINUTILS_VERSION_RELEASE 6

/* COIN_INT64_T */
#define COIN_INT64_T int64_t
/* COIN_UINT64_T */
#define COIN_UINT64_T uint64_t
/* COIN_INTPTR_T */
#define COIN_INTPTR_T intptr_t

#endif
