#ifndef __CONFIG_CGL_H__
#define __CONFIG_CGL_H__

/* CGL_VERSION */
#define CGL_VERSION "0.60.5"
/* CGL_VERSION_MAJOR */
#define CGL_VERSION_MAJOR 0
/* CGL_VERSION_MINOR */
#define CGL_VERSION_MINOR 60
/* CGL_VERSION_RELEASE */
#define CGL_VERSION_RELEASE 5

#endif
