// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/sat/cp_model_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ortools_2fsat_2fcp_5fmodel_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ortools_2fsat_2fcp_5fmodel_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ortools/sat/cp_model.pb.h"
#include "ortools/sat/sat_parameters.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ortools_2fsat_2fcp_5fmodel_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ortools_2fsat_2fcp_5fmodel_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ortools_2fsat_2fcp_5fmodel_5fservice_2eproto;
namespace operations_research {
namespace sat {
namespace v1 {
class CpSolverRequest;
struct CpSolverRequestDefaultTypeInternal;
extern CpSolverRequestDefaultTypeInternal _CpSolverRequest_default_instance_;
}  // namespace v1
}  // namespace sat
}  // namespace operations_research
PROTOBUF_NAMESPACE_OPEN
template<> ::operations_research::sat::v1::CpSolverRequest* Arena::CreateMaybeMessage<::operations_research::sat::v1::CpSolverRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace operations_research {
namespace sat {
namespace v1 {

// ===================================================================

class CpSolverRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.sat.v1.CpSolverRequest) */ {
 public:
  inline CpSolverRequest() : CpSolverRequest(nullptr) {}
  ~CpSolverRequest() override;
  explicit PROTOBUF_CONSTEXPR CpSolverRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CpSolverRequest(const CpSolverRequest& from);
  CpSolverRequest(CpSolverRequest&& from) noexcept
    : CpSolverRequest() {
    *this = ::std::move(from);
  }

  inline CpSolverRequest& operator=(const CpSolverRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CpSolverRequest& operator=(CpSolverRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CpSolverRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CpSolverRequest* internal_default_instance() {
    return reinterpret_cast<const CpSolverRequest*>(
               &_CpSolverRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CpSolverRequest& a, CpSolverRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CpSolverRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CpSolverRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CpSolverRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CpSolverRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CpSolverRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CpSolverRequest& from) {
    CpSolverRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CpSolverRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.sat.v1.CpSolverRequest";
  }
  protected:
  explicit CpSolverRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModelFieldNumber = 1,
    kParametersFieldNumber = 3,
  };
  // .operations_research.sat.CpModelProto model = 1;
  bool has_model() const;
  private:
  bool _internal_has_model() const;
  public:
  void clear_model();
  const ::operations_research::sat::CpModelProto& model() const;
  PROTOBUF_NODISCARD ::operations_research::sat::CpModelProto* release_model();
  ::operations_research::sat::CpModelProto* mutable_model();
  void set_allocated_model(::operations_research::sat::CpModelProto* model);
  private:
  const ::operations_research::sat::CpModelProto& _internal_model() const;
  ::operations_research::sat::CpModelProto* _internal_mutable_model();
  public:
  void unsafe_arena_set_allocated_model(
      ::operations_research::sat::CpModelProto* model);
  ::operations_research::sat::CpModelProto* unsafe_arena_release_model();

  // .operations_research.sat.SatParameters parameters = 3;
  bool has_parameters() const;
  private:
  bool _internal_has_parameters() const;
  public:
  void clear_parameters();
  const ::operations_research::sat::SatParameters& parameters() const;
  PROTOBUF_NODISCARD ::operations_research::sat::SatParameters* release_parameters();
  ::operations_research::sat::SatParameters* mutable_parameters();
  void set_allocated_parameters(::operations_research::sat::SatParameters* parameters);
  private:
  const ::operations_research::sat::SatParameters& _internal_parameters() const;
  ::operations_research::sat::SatParameters* _internal_mutable_parameters();
  public:
  void unsafe_arena_set_allocated_parameters(
      ::operations_research::sat::SatParameters* parameters);
  ::operations_research::sat::SatParameters* unsafe_arena_release_parameters();

  // @@protoc_insertion_point(class_scope:operations_research.sat.v1.CpSolverRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::operations_research::sat::CpModelProto* model_;
    ::operations_research::sat::SatParameters* parameters_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fsat_2fcp_5fmodel_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CpSolverRequest

// .operations_research.sat.CpModelProto model = 1;
inline bool CpSolverRequest::_internal_has_model() const {
  return this != internal_default_instance() && _impl_.model_ != nullptr;
}
inline bool CpSolverRequest::has_model() const {
  return _internal_has_model();
}
inline const ::operations_research::sat::CpModelProto& CpSolverRequest::_internal_model() const {
  const ::operations_research::sat::CpModelProto* p = _impl_.model_;
  return p != nullptr ? *p : reinterpret_cast<const ::operations_research::sat::CpModelProto&>(
      ::operations_research::sat::_CpModelProto_default_instance_);
}
inline const ::operations_research::sat::CpModelProto& CpSolverRequest::model() const {
  // @@protoc_insertion_point(field_get:operations_research.sat.v1.CpSolverRequest.model)
  return _internal_model();
}
inline void CpSolverRequest::unsafe_arena_set_allocated_model(
    ::operations_research::sat::CpModelProto* model) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_);
  }
  _impl_.model_ = model;
  if (model) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:operations_research.sat.v1.CpSolverRequest.model)
}
inline ::operations_research::sat::CpModelProto* CpSolverRequest::release_model() {
  
  ::operations_research::sat::CpModelProto* temp = _impl_.model_;
  _impl_.model_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::operations_research::sat::CpModelProto* CpSolverRequest::unsafe_arena_release_model() {
  // @@protoc_insertion_point(field_release:operations_research.sat.v1.CpSolverRequest.model)
  
  ::operations_research::sat::CpModelProto* temp = _impl_.model_;
  _impl_.model_ = nullptr;
  return temp;
}
inline ::operations_research::sat::CpModelProto* CpSolverRequest::_internal_mutable_model() {
  
  if (_impl_.model_ == nullptr) {
    auto* p = CreateMaybeMessage<::operations_research::sat::CpModelProto>(GetArenaForAllocation());
    _impl_.model_ = p;
  }
  return _impl_.model_;
}
inline ::operations_research::sat::CpModelProto* CpSolverRequest::mutable_model() {
  ::operations_research::sat::CpModelProto* _msg = _internal_mutable_model();
  // @@protoc_insertion_point(field_mutable:operations_research.sat.v1.CpSolverRequest.model)
  return _msg;
}
inline void CpSolverRequest::set_allocated_model(::operations_research::sat::CpModelProto* model) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_);
  }
  if (model) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(model));
    if (message_arena != submessage_arena) {
      model = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, model, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.model_ = model;
  // @@protoc_insertion_point(field_set_allocated:operations_research.sat.v1.CpSolverRequest.model)
}

// .operations_research.sat.SatParameters parameters = 3;
inline bool CpSolverRequest::_internal_has_parameters() const {
  return this != internal_default_instance() && _impl_.parameters_ != nullptr;
}
inline bool CpSolverRequest::has_parameters() const {
  return _internal_has_parameters();
}
inline const ::operations_research::sat::SatParameters& CpSolverRequest::_internal_parameters() const {
  const ::operations_research::sat::SatParameters* p = _impl_.parameters_;
  return p != nullptr ? *p : reinterpret_cast<const ::operations_research::sat::SatParameters&>(
      ::operations_research::sat::_SatParameters_default_instance_);
}
inline const ::operations_research::sat::SatParameters& CpSolverRequest::parameters() const {
  // @@protoc_insertion_point(field_get:operations_research.sat.v1.CpSolverRequest.parameters)
  return _internal_parameters();
}
inline void CpSolverRequest::unsafe_arena_set_allocated_parameters(
    ::operations_research::sat::SatParameters* parameters) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.parameters_);
  }
  _impl_.parameters_ = parameters;
  if (parameters) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:operations_research.sat.v1.CpSolverRequest.parameters)
}
inline ::operations_research::sat::SatParameters* CpSolverRequest::release_parameters() {
  
  ::operations_research::sat::SatParameters* temp = _impl_.parameters_;
  _impl_.parameters_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::operations_research::sat::SatParameters* CpSolverRequest::unsafe_arena_release_parameters() {
  // @@protoc_insertion_point(field_release:operations_research.sat.v1.CpSolverRequest.parameters)
  
  ::operations_research::sat::SatParameters* temp = _impl_.parameters_;
  _impl_.parameters_ = nullptr;
  return temp;
}
inline ::operations_research::sat::SatParameters* CpSolverRequest::_internal_mutable_parameters() {
  
  if (_impl_.parameters_ == nullptr) {
    auto* p = CreateMaybeMessage<::operations_research::sat::SatParameters>(GetArenaForAllocation());
    _impl_.parameters_ = p;
  }
  return _impl_.parameters_;
}
inline ::operations_research::sat::SatParameters* CpSolverRequest::mutable_parameters() {
  ::operations_research::sat::SatParameters* _msg = _internal_mutable_parameters();
  // @@protoc_insertion_point(field_mutable:operations_research.sat.v1.CpSolverRequest.parameters)
  return _msg;
}
inline void CpSolverRequest::set_allocated_parameters(::operations_research::sat::SatParameters* parameters) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.parameters_);
  }
  if (parameters) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(parameters));
    if (message_arena != submessage_arena) {
      parameters = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, parameters, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.parameters_ = parameters;
  // @@protoc_insertion_point(field_set_allocated:operations_research.sat.v1.CpSolverRequest.parameters)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace sat
}  // namespace operations_research

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ortools_2fsat_2fcp_5fmodel_5fservice_2eproto
