// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/scheduling/rcpsp.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ortools_2fscheduling_2frcpsp_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ortools_2fscheduling_2frcpsp_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ortools_2fscheduling_2frcpsp_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ortools_2fscheduling_2frcpsp_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ortools_2fscheduling_2frcpsp_2eproto;
namespace operations_research {
namespace scheduling {
namespace rcpsp {
class PerRecipeDelays;
struct PerRecipeDelaysDefaultTypeInternal;
extern PerRecipeDelaysDefaultTypeInternal _PerRecipeDelays_default_instance_;
class PerSuccessorDelays;
struct PerSuccessorDelaysDefaultTypeInternal;
extern PerSuccessorDelaysDefaultTypeInternal _PerSuccessorDelays_default_instance_;
class RcpspAssignment;
struct RcpspAssignmentDefaultTypeInternal;
extern RcpspAssignmentDefaultTypeInternal _RcpspAssignment_default_instance_;
class RcpspProblem;
struct RcpspProblemDefaultTypeInternal;
extern RcpspProblemDefaultTypeInternal _RcpspProblem_default_instance_;
class Recipe;
struct RecipeDefaultTypeInternal;
extern RecipeDefaultTypeInternal _Recipe_default_instance_;
class Resource;
struct ResourceDefaultTypeInternal;
extern ResourceDefaultTypeInternal _Resource_default_instance_;
class Task;
struct TaskDefaultTypeInternal;
extern TaskDefaultTypeInternal _Task_default_instance_;
}  // namespace rcpsp
}  // namespace scheduling
}  // namespace operations_research
PROTOBUF_NAMESPACE_OPEN
template<> ::operations_research::scheduling::rcpsp::PerRecipeDelays* Arena::CreateMaybeMessage<::operations_research::scheduling::rcpsp::PerRecipeDelays>(Arena*);
template<> ::operations_research::scheduling::rcpsp::PerSuccessorDelays* Arena::CreateMaybeMessage<::operations_research::scheduling::rcpsp::PerSuccessorDelays>(Arena*);
template<> ::operations_research::scheduling::rcpsp::RcpspAssignment* Arena::CreateMaybeMessage<::operations_research::scheduling::rcpsp::RcpspAssignment>(Arena*);
template<> ::operations_research::scheduling::rcpsp::RcpspProblem* Arena::CreateMaybeMessage<::operations_research::scheduling::rcpsp::RcpspProblem>(Arena*);
template<> ::operations_research::scheduling::rcpsp::Recipe* Arena::CreateMaybeMessage<::operations_research::scheduling::rcpsp::Recipe>(Arena*);
template<> ::operations_research::scheduling::rcpsp::Resource* Arena::CreateMaybeMessage<::operations_research::scheduling::rcpsp::Resource>(Arena*);
template<> ::operations_research::scheduling::rcpsp::Task* Arena::CreateMaybeMessage<::operations_research::scheduling::rcpsp::Task>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace operations_research {
namespace scheduling {
namespace rcpsp {

// ===================================================================

class Resource final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.scheduling.rcpsp.Resource) */ {
 public:
  inline Resource() : Resource(nullptr) {}
  ~Resource() override;
  explicit PROTOBUF_CONSTEXPR Resource(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Resource(const Resource& from);
  Resource(Resource&& from) noexcept
    : Resource() {
    *this = ::std::move(from);
  }

  inline Resource& operator=(const Resource& from) {
    CopyFrom(from);
    return *this;
  }
  inline Resource& operator=(Resource&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Resource& default_instance() {
    return *internal_default_instance();
  }
  static inline const Resource* internal_default_instance() {
    return reinterpret_cast<const Resource*>(
               &_Resource_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Resource& a, Resource& b) {
    a.Swap(&b);
  }
  inline void Swap(Resource* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Resource* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Resource* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Resource>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Resource& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Resource& from) {
    Resource::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Resource* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.scheduling.rcpsp.Resource";
  }
  protected:
  explicit Resource(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMaxCapacityFieldNumber = 1,
    kMinCapacityFieldNumber = 2,
    kRenewableFieldNumber = 3,
    kUnitCostFieldNumber = 4,
  };
  // int32 max_capacity = 1;
  void clear_max_capacity();
  int32_t max_capacity() const;
  void set_max_capacity(int32_t value);
  private:
  int32_t _internal_max_capacity() const;
  void _internal_set_max_capacity(int32_t value);
  public:

  // int32 min_capacity = 2;
  void clear_min_capacity();
  int32_t min_capacity() const;
  void set_min_capacity(int32_t value);
  private:
  int32_t _internal_min_capacity() const;
  void _internal_set_min_capacity(int32_t value);
  public:

  // bool renewable = 3;
  void clear_renewable();
  bool renewable() const;
  void set_renewable(bool value);
  private:
  bool _internal_renewable() const;
  void _internal_set_renewable(bool value);
  public:

  // int32 unit_cost = 4;
  void clear_unit_cost();
  int32_t unit_cost() const;
  void set_unit_cost(int32_t value);
  private:
  int32_t _internal_unit_cost() const;
  void _internal_set_unit_cost(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:operations_research.scheduling.rcpsp.Resource)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t max_capacity_;
    int32_t min_capacity_;
    bool renewable_;
    int32_t unit_cost_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fscheduling_2frcpsp_2eproto;
};
// -------------------------------------------------------------------

class Recipe final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.scheduling.rcpsp.Recipe) */ {
 public:
  inline Recipe() : Recipe(nullptr) {}
  ~Recipe() override;
  explicit PROTOBUF_CONSTEXPR Recipe(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Recipe(const Recipe& from);
  Recipe(Recipe&& from) noexcept
    : Recipe() {
    *this = ::std::move(from);
  }

  inline Recipe& operator=(const Recipe& from) {
    CopyFrom(from);
    return *this;
  }
  inline Recipe& operator=(Recipe&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Recipe& default_instance() {
    return *internal_default_instance();
  }
  static inline const Recipe* internal_default_instance() {
    return reinterpret_cast<const Recipe*>(
               &_Recipe_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Recipe& a, Recipe& b) {
    a.Swap(&b);
  }
  inline void Swap(Recipe* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Recipe* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Recipe* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Recipe>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Recipe& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Recipe& from) {
    Recipe::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Recipe* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.scheduling.rcpsp.Recipe";
  }
  protected:
  explicit Recipe(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDemandsFieldNumber = 2,
    kResourcesFieldNumber = 3,
    kDurationFieldNumber = 1,
  };
  // repeated int32 demands = 2;
  int demands_size() const;
  private:
  int _internal_demands_size() const;
  public:
  void clear_demands();
  private:
  int32_t _internal_demands(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_demands() const;
  void _internal_add_demands(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_demands();
  public:
  int32_t demands(int index) const;
  void set_demands(int index, int32_t value);
  void add_demands(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      demands() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_demands();

  // repeated int32 resources = 3;
  int resources_size() const;
  private:
  int _internal_resources_size() const;
  public:
  void clear_resources();
  private:
  int32_t _internal_resources(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_resources() const;
  void _internal_add_resources(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_resources();
  public:
  int32_t resources(int index) const;
  void set_resources(int index, int32_t value);
  void add_resources(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      resources() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_resources();

  // int32 duration = 1;
  void clear_duration();
  int32_t duration() const;
  void set_duration(int32_t value);
  private:
  int32_t _internal_duration() const;
  void _internal_set_duration(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:operations_research.scheduling.rcpsp.Recipe)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > demands_;
    mutable std::atomic<int> _demands_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > resources_;
    mutable std::atomic<int> _resources_cached_byte_size_;
    int32_t duration_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fscheduling_2frcpsp_2eproto;
};
// -------------------------------------------------------------------

class PerRecipeDelays final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.scheduling.rcpsp.PerRecipeDelays) */ {
 public:
  inline PerRecipeDelays() : PerRecipeDelays(nullptr) {}
  ~PerRecipeDelays() override;
  explicit PROTOBUF_CONSTEXPR PerRecipeDelays(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PerRecipeDelays(const PerRecipeDelays& from);
  PerRecipeDelays(PerRecipeDelays&& from) noexcept
    : PerRecipeDelays() {
    *this = ::std::move(from);
  }

  inline PerRecipeDelays& operator=(const PerRecipeDelays& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerRecipeDelays& operator=(PerRecipeDelays&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PerRecipeDelays& default_instance() {
    return *internal_default_instance();
  }
  static inline const PerRecipeDelays* internal_default_instance() {
    return reinterpret_cast<const PerRecipeDelays*>(
               &_PerRecipeDelays_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PerRecipeDelays& a, PerRecipeDelays& b) {
    a.Swap(&b);
  }
  inline void Swap(PerRecipeDelays* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PerRecipeDelays* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PerRecipeDelays* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PerRecipeDelays>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PerRecipeDelays& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PerRecipeDelays& from) {
    PerRecipeDelays::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerRecipeDelays* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.scheduling.rcpsp.PerRecipeDelays";
  }
  protected:
  explicit PerRecipeDelays(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMinDelaysFieldNumber = 1,
  };
  // repeated int32 min_delays = 1;
  int min_delays_size() const;
  private:
  int _internal_min_delays_size() const;
  public:
  void clear_min_delays();
  private:
  int32_t _internal_min_delays(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_min_delays() const;
  void _internal_add_min_delays(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_min_delays();
  public:
  int32_t min_delays(int index) const;
  void set_min_delays(int index, int32_t value);
  void add_min_delays(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      min_delays() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_min_delays();

  // @@protoc_insertion_point(class_scope:operations_research.scheduling.rcpsp.PerRecipeDelays)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > min_delays_;
    mutable std::atomic<int> _min_delays_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fscheduling_2frcpsp_2eproto;
};
// -------------------------------------------------------------------

class PerSuccessorDelays final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.scheduling.rcpsp.PerSuccessorDelays) */ {
 public:
  inline PerSuccessorDelays() : PerSuccessorDelays(nullptr) {}
  ~PerSuccessorDelays() override;
  explicit PROTOBUF_CONSTEXPR PerSuccessorDelays(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PerSuccessorDelays(const PerSuccessorDelays& from);
  PerSuccessorDelays(PerSuccessorDelays&& from) noexcept
    : PerSuccessorDelays() {
    *this = ::std::move(from);
  }

  inline PerSuccessorDelays& operator=(const PerSuccessorDelays& from) {
    CopyFrom(from);
    return *this;
  }
  inline PerSuccessorDelays& operator=(PerSuccessorDelays&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PerSuccessorDelays& default_instance() {
    return *internal_default_instance();
  }
  static inline const PerSuccessorDelays* internal_default_instance() {
    return reinterpret_cast<const PerSuccessorDelays*>(
               &_PerSuccessorDelays_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PerSuccessorDelays& a, PerSuccessorDelays& b) {
    a.Swap(&b);
  }
  inline void Swap(PerSuccessorDelays* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PerSuccessorDelays* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PerSuccessorDelays* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PerSuccessorDelays>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PerSuccessorDelays& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PerSuccessorDelays& from) {
    PerSuccessorDelays::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerSuccessorDelays* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.scheduling.rcpsp.PerSuccessorDelays";
  }
  protected:
  explicit PerSuccessorDelays(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecipeDelaysFieldNumber = 1,
  };
  // repeated .operations_research.scheduling.rcpsp.PerRecipeDelays recipe_delays = 1;
  int recipe_delays_size() const;
  private:
  int _internal_recipe_delays_size() const;
  public:
  void clear_recipe_delays();
  ::operations_research::scheduling::rcpsp::PerRecipeDelays* mutable_recipe_delays(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerRecipeDelays >*
      mutable_recipe_delays();
  private:
  const ::operations_research::scheduling::rcpsp::PerRecipeDelays& _internal_recipe_delays(int index) const;
  ::operations_research::scheduling::rcpsp::PerRecipeDelays* _internal_add_recipe_delays();
  public:
  const ::operations_research::scheduling::rcpsp::PerRecipeDelays& recipe_delays(int index) const;
  ::operations_research::scheduling::rcpsp::PerRecipeDelays* add_recipe_delays();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerRecipeDelays >&
      recipe_delays() const;

  // @@protoc_insertion_point(class_scope:operations_research.scheduling.rcpsp.PerSuccessorDelays)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerRecipeDelays > recipe_delays_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fscheduling_2frcpsp_2eproto;
};
// -------------------------------------------------------------------

class Task final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.scheduling.rcpsp.Task) */ {
 public:
  inline Task() : Task(nullptr) {}
  ~Task() override;
  explicit PROTOBUF_CONSTEXPR Task(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Task(const Task& from);
  Task(Task&& from) noexcept
    : Task() {
    *this = ::std::move(from);
  }

  inline Task& operator=(const Task& from) {
    CopyFrom(from);
    return *this;
  }
  inline Task& operator=(Task&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Task& default_instance() {
    return *internal_default_instance();
  }
  static inline const Task* internal_default_instance() {
    return reinterpret_cast<const Task*>(
               &_Task_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Task& a, Task& b) {
    a.Swap(&b);
  }
  inline void Swap(Task* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Task* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Task* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Task>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Task& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Task& from) {
    Task::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Task* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.scheduling.rcpsp.Task";
  }
  protected:
  explicit Task(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessorsFieldNumber = 1,
    kRecipesFieldNumber = 2,
    kSuccessorDelaysFieldNumber = 3,
  };
  // repeated int32 successors = 1;
  int successors_size() const;
  private:
  int _internal_successors_size() const;
  public:
  void clear_successors();
  private:
  int32_t _internal_successors(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_successors() const;
  void _internal_add_successors(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_successors();
  public:
  int32_t successors(int index) const;
  void set_successors(int index, int32_t value);
  void add_successors(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      successors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_successors();

  // repeated .operations_research.scheduling.rcpsp.Recipe recipes = 2;
  int recipes_size() const;
  private:
  int _internal_recipes_size() const;
  public:
  void clear_recipes();
  ::operations_research::scheduling::rcpsp::Recipe* mutable_recipes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Recipe >*
      mutable_recipes();
  private:
  const ::operations_research::scheduling::rcpsp::Recipe& _internal_recipes(int index) const;
  ::operations_research::scheduling::rcpsp::Recipe* _internal_add_recipes();
  public:
  const ::operations_research::scheduling::rcpsp::Recipe& recipes(int index) const;
  ::operations_research::scheduling::rcpsp::Recipe* add_recipes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Recipe >&
      recipes() const;

  // repeated .operations_research.scheduling.rcpsp.PerSuccessorDelays successor_delays = 3;
  int successor_delays_size() const;
  private:
  int _internal_successor_delays_size() const;
  public:
  void clear_successor_delays();
  ::operations_research::scheduling::rcpsp::PerSuccessorDelays* mutable_successor_delays(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerSuccessorDelays >*
      mutable_successor_delays();
  private:
  const ::operations_research::scheduling::rcpsp::PerSuccessorDelays& _internal_successor_delays(int index) const;
  ::operations_research::scheduling::rcpsp::PerSuccessorDelays* _internal_add_successor_delays();
  public:
  const ::operations_research::scheduling::rcpsp::PerSuccessorDelays& successor_delays(int index) const;
  ::operations_research::scheduling::rcpsp::PerSuccessorDelays* add_successor_delays();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerSuccessorDelays >&
      successor_delays() const;

  // @@protoc_insertion_point(class_scope:operations_research.scheduling.rcpsp.Task)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > successors_;
    mutable std::atomic<int> _successors_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Recipe > recipes_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerSuccessorDelays > successor_delays_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fscheduling_2frcpsp_2eproto;
};
// -------------------------------------------------------------------

class RcpspProblem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.scheduling.rcpsp.RcpspProblem) */ {
 public:
  inline RcpspProblem() : RcpspProblem(nullptr) {}
  ~RcpspProblem() override;
  explicit PROTOBUF_CONSTEXPR RcpspProblem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RcpspProblem(const RcpspProblem& from);
  RcpspProblem(RcpspProblem&& from) noexcept
    : RcpspProblem() {
    *this = ::std::move(from);
  }

  inline RcpspProblem& operator=(const RcpspProblem& from) {
    CopyFrom(from);
    return *this;
  }
  inline RcpspProblem& operator=(RcpspProblem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RcpspProblem& default_instance() {
    return *internal_default_instance();
  }
  static inline const RcpspProblem* internal_default_instance() {
    return reinterpret_cast<const RcpspProblem*>(
               &_RcpspProblem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(RcpspProblem& a, RcpspProblem& b) {
    a.Swap(&b);
  }
  inline void Swap(RcpspProblem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RcpspProblem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RcpspProblem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RcpspProblem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RcpspProblem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RcpspProblem& from) {
    RcpspProblem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RcpspProblem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.scheduling.rcpsp.RcpspProblem";
  }
  protected:
  explicit RcpspProblem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResourcesFieldNumber = 1,
    kTasksFieldNumber = 2,
    kBasedataFieldNumber = 12,
    kNameFieldNumber = 14,
    kIsConsumerProducerFieldNumber = 3,
    kIsResourceInvestmentFieldNumber = 4,
    kIsRcpspMaxFieldNumber = 5,
    kDeadlineFieldNumber = 6,
    kHorizonFieldNumber = 7,
    kReleaseDateFieldNumber = 8,
    kTardinessCostFieldNumber = 9,
    kMpmTimeFieldNumber = 10,
    kSeedFieldNumber = 11,
    kDueDateFieldNumber = 13,
  };
  // repeated .operations_research.scheduling.rcpsp.Resource resources = 1;
  int resources_size() const;
  private:
  int _internal_resources_size() const;
  public:
  void clear_resources();
  ::operations_research::scheduling::rcpsp::Resource* mutable_resources(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Resource >*
      mutable_resources();
  private:
  const ::operations_research::scheduling::rcpsp::Resource& _internal_resources(int index) const;
  ::operations_research::scheduling::rcpsp::Resource* _internal_add_resources();
  public:
  const ::operations_research::scheduling::rcpsp::Resource& resources(int index) const;
  ::operations_research::scheduling::rcpsp::Resource* add_resources();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Resource >&
      resources() const;

  // repeated .operations_research.scheduling.rcpsp.Task tasks = 2;
  int tasks_size() const;
  private:
  int _internal_tasks_size() const;
  public:
  void clear_tasks();
  ::operations_research::scheduling::rcpsp::Task* mutable_tasks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Task >*
      mutable_tasks();
  private:
  const ::operations_research::scheduling::rcpsp::Task& _internal_tasks(int index) const;
  ::operations_research::scheduling::rcpsp::Task* _internal_add_tasks();
  public:
  const ::operations_research::scheduling::rcpsp::Task& tasks(int index) const;
  ::operations_research::scheduling::rcpsp::Task* add_tasks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Task >&
      tasks() const;

  // string basedata = 12;
  void clear_basedata();
  const std::string& basedata() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_basedata(ArgT0&& arg0, ArgT... args);
  std::string* mutable_basedata();
  PROTOBUF_NODISCARD std::string* release_basedata();
  void set_allocated_basedata(std::string* basedata);
  private:
  const std::string& _internal_basedata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_basedata(const std::string& value);
  std::string* _internal_mutable_basedata();
  public:

  // string name = 14;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bool is_consumer_producer = 3;
  void clear_is_consumer_producer();
  bool is_consumer_producer() const;
  void set_is_consumer_producer(bool value);
  private:
  bool _internal_is_consumer_producer() const;
  void _internal_set_is_consumer_producer(bool value);
  public:

  // bool is_resource_investment = 4;
  void clear_is_resource_investment();
  bool is_resource_investment() const;
  void set_is_resource_investment(bool value);
  private:
  bool _internal_is_resource_investment() const;
  void _internal_set_is_resource_investment(bool value);
  public:

  // bool is_rcpsp_max = 5;
  void clear_is_rcpsp_max();
  bool is_rcpsp_max() const;
  void set_is_rcpsp_max(bool value);
  private:
  bool _internal_is_rcpsp_max() const;
  void _internal_set_is_rcpsp_max(bool value);
  public:

  // int32 deadline = 6;
  void clear_deadline();
  int32_t deadline() const;
  void set_deadline(int32_t value);
  private:
  int32_t _internal_deadline() const;
  void _internal_set_deadline(int32_t value);
  public:

  // int32 horizon = 7;
  void clear_horizon();
  int32_t horizon() const;
  void set_horizon(int32_t value);
  private:
  int32_t _internal_horizon() const;
  void _internal_set_horizon(int32_t value);
  public:

  // int32 release_date = 8;
  void clear_release_date();
  int32_t release_date() const;
  void set_release_date(int32_t value);
  private:
  int32_t _internal_release_date() const;
  void _internal_set_release_date(int32_t value);
  public:

  // int32 tardiness_cost = 9;
  void clear_tardiness_cost();
  int32_t tardiness_cost() const;
  void set_tardiness_cost(int32_t value);
  private:
  int32_t _internal_tardiness_cost() const;
  void _internal_set_tardiness_cost(int32_t value);
  public:

  // int32 mpm_time = 10;
  void clear_mpm_time();
  int32_t mpm_time() const;
  void set_mpm_time(int32_t value);
  private:
  int32_t _internal_mpm_time() const;
  void _internal_set_mpm_time(int32_t value);
  public:

  // int64 seed = 11;
  void clear_seed();
  int64_t seed() const;
  void set_seed(int64_t value);
  private:
  int64_t _internal_seed() const;
  void _internal_set_seed(int64_t value);
  public:

  // int32 due_date = 13;
  void clear_due_date();
  int32_t due_date() const;
  void set_due_date(int32_t value);
  private:
  int32_t _internal_due_date() const;
  void _internal_set_due_date(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:operations_research.scheduling.rcpsp.RcpspProblem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Resource > resources_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Task > tasks_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr basedata_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    bool is_consumer_producer_;
    bool is_resource_investment_;
    bool is_rcpsp_max_;
    int32_t deadline_;
    int32_t horizon_;
    int32_t release_date_;
    int32_t tardiness_cost_;
    int32_t mpm_time_;
    int64_t seed_;
    int32_t due_date_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fscheduling_2frcpsp_2eproto;
};
// -------------------------------------------------------------------

class RcpspAssignment final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:operations_research.scheduling.rcpsp.RcpspAssignment) */ {
 public:
  inline RcpspAssignment() : RcpspAssignment(nullptr) {}
  ~RcpspAssignment() override;
  explicit PROTOBUF_CONSTEXPR RcpspAssignment(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RcpspAssignment(const RcpspAssignment& from);
  RcpspAssignment(RcpspAssignment&& from) noexcept
    : RcpspAssignment() {
    *this = ::std::move(from);
  }

  inline RcpspAssignment& operator=(const RcpspAssignment& from) {
    CopyFrom(from);
    return *this;
  }
  inline RcpspAssignment& operator=(RcpspAssignment&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RcpspAssignment& default_instance() {
    return *internal_default_instance();
  }
  static inline const RcpspAssignment* internal_default_instance() {
    return reinterpret_cast<const RcpspAssignment*>(
               &_RcpspAssignment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(RcpspAssignment& a, RcpspAssignment& b) {
    a.Swap(&b);
  }
  inline void Swap(RcpspAssignment* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RcpspAssignment* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RcpspAssignment* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RcpspAssignment>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RcpspAssignment& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RcpspAssignment& from) {
    RcpspAssignment::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RcpspAssignment* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "operations_research.scheduling.rcpsp.RcpspAssignment";
  }
  protected:
  explicit RcpspAssignment(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartOfTaskFieldNumber = 1,
    kSelectedRecipeOfTaskFieldNumber = 2,
  };
  // repeated int64 start_of_task = 1;
  int start_of_task_size() const;
  private:
  int _internal_start_of_task_size() const;
  public:
  void clear_start_of_task();
  private:
  int64_t _internal_start_of_task(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      _internal_start_of_task() const;
  void _internal_add_start_of_task(int64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      _internal_mutable_start_of_task();
  public:
  int64_t start_of_task(int index) const;
  void set_start_of_task(int index, int64_t value);
  void add_start_of_task(int64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      start_of_task() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      mutable_start_of_task();

  // repeated int32 selected_recipe_of_task = 2;
  int selected_recipe_of_task_size() const;
  private:
  int _internal_selected_recipe_of_task_size() const;
  public:
  void clear_selected_recipe_of_task();
  private:
  int32_t _internal_selected_recipe_of_task(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_selected_recipe_of_task() const;
  void _internal_add_selected_recipe_of_task(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_selected_recipe_of_task();
  public:
  int32_t selected_recipe_of_task(int index) const;
  void set_selected_recipe_of_task(int index, int32_t value);
  void add_selected_recipe_of_task(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      selected_recipe_of_task() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_selected_recipe_of_task();

  // @@protoc_insertion_point(class_scope:operations_research.scheduling.rcpsp.RcpspAssignment)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t > start_of_task_;
    mutable std::atomic<int> _start_of_task_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > selected_recipe_of_task_;
    mutable std::atomic<int> _selected_recipe_of_task_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ortools_2fscheduling_2frcpsp_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Resource

// int32 max_capacity = 1;
inline void Resource::clear_max_capacity() {
  _impl_.max_capacity_ = 0;
}
inline int32_t Resource::_internal_max_capacity() const {
  return _impl_.max_capacity_;
}
inline int32_t Resource::max_capacity() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Resource.max_capacity)
  return _internal_max_capacity();
}
inline void Resource::_internal_set_max_capacity(int32_t value) {
  
  _impl_.max_capacity_ = value;
}
inline void Resource::set_max_capacity(int32_t value) {
  _internal_set_max_capacity(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.Resource.max_capacity)
}

// int32 min_capacity = 2;
inline void Resource::clear_min_capacity() {
  _impl_.min_capacity_ = 0;
}
inline int32_t Resource::_internal_min_capacity() const {
  return _impl_.min_capacity_;
}
inline int32_t Resource::min_capacity() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Resource.min_capacity)
  return _internal_min_capacity();
}
inline void Resource::_internal_set_min_capacity(int32_t value) {
  
  _impl_.min_capacity_ = value;
}
inline void Resource::set_min_capacity(int32_t value) {
  _internal_set_min_capacity(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.Resource.min_capacity)
}

// bool renewable = 3;
inline void Resource::clear_renewable() {
  _impl_.renewable_ = false;
}
inline bool Resource::_internal_renewable() const {
  return _impl_.renewable_;
}
inline bool Resource::renewable() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Resource.renewable)
  return _internal_renewable();
}
inline void Resource::_internal_set_renewable(bool value) {
  
  _impl_.renewable_ = value;
}
inline void Resource::set_renewable(bool value) {
  _internal_set_renewable(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.Resource.renewable)
}

// int32 unit_cost = 4;
inline void Resource::clear_unit_cost() {
  _impl_.unit_cost_ = 0;
}
inline int32_t Resource::_internal_unit_cost() const {
  return _impl_.unit_cost_;
}
inline int32_t Resource::unit_cost() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Resource.unit_cost)
  return _internal_unit_cost();
}
inline void Resource::_internal_set_unit_cost(int32_t value) {
  
  _impl_.unit_cost_ = value;
}
inline void Resource::set_unit_cost(int32_t value) {
  _internal_set_unit_cost(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.Resource.unit_cost)
}

// -------------------------------------------------------------------

// Recipe

// int32 duration = 1;
inline void Recipe::clear_duration() {
  _impl_.duration_ = 0;
}
inline int32_t Recipe::_internal_duration() const {
  return _impl_.duration_;
}
inline int32_t Recipe::duration() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Recipe.duration)
  return _internal_duration();
}
inline void Recipe::_internal_set_duration(int32_t value) {
  
  _impl_.duration_ = value;
}
inline void Recipe::set_duration(int32_t value) {
  _internal_set_duration(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.Recipe.duration)
}

// repeated int32 demands = 2;
inline int Recipe::_internal_demands_size() const {
  return _impl_.demands_.size();
}
inline int Recipe::demands_size() const {
  return _internal_demands_size();
}
inline void Recipe::clear_demands() {
  _impl_.demands_.Clear();
}
inline int32_t Recipe::_internal_demands(int index) const {
  return _impl_.demands_.Get(index);
}
inline int32_t Recipe::demands(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Recipe.demands)
  return _internal_demands(index);
}
inline void Recipe::set_demands(int index, int32_t value) {
  _impl_.demands_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.Recipe.demands)
}
inline void Recipe::_internal_add_demands(int32_t value) {
  _impl_.demands_.Add(value);
}
inline void Recipe::add_demands(int32_t value) {
  _internal_add_demands(value);
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.Recipe.demands)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Recipe::_internal_demands() const {
  return _impl_.demands_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Recipe::demands() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.Recipe.demands)
  return _internal_demands();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Recipe::_internal_mutable_demands() {
  return &_impl_.demands_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Recipe::mutable_demands() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.Recipe.demands)
  return _internal_mutable_demands();
}

// repeated int32 resources = 3;
inline int Recipe::_internal_resources_size() const {
  return _impl_.resources_.size();
}
inline int Recipe::resources_size() const {
  return _internal_resources_size();
}
inline void Recipe::clear_resources() {
  _impl_.resources_.Clear();
}
inline int32_t Recipe::_internal_resources(int index) const {
  return _impl_.resources_.Get(index);
}
inline int32_t Recipe::resources(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Recipe.resources)
  return _internal_resources(index);
}
inline void Recipe::set_resources(int index, int32_t value) {
  _impl_.resources_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.Recipe.resources)
}
inline void Recipe::_internal_add_resources(int32_t value) {
  _impl_.resources_.Add(value);
}
inline void Recipe::add_resources(int32_t value) {
  _internal_add_resources(value);
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.Recipe.resources)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Recipe::_internal_resources() const {
  return _impl_.resources_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Recipe::resources() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.Recipe.resources)
  return _internal_resources();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Recipe::_internal_mutable_resources() {
  return &_impl_.resources_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Recipe::mutable_resources() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.Recipe.resources)
  return _internal_mutable_resources();
}

// -------------------------------------------------------------------

// PerRecipeDelays

// repeated int32 min_delays = 1;
inline int PerRecipeDelays::_internal_min_delays_size() const {
  return _impl_.min_delays_.size();
}
inline int PerRecipeDelays::min_delays_size() const {
  return _internal_min_delays_size();
}
inline void PerRecipeDelays::clear_min_delays() {
  _impl_.min_delays_.Clear();
}
inline int32_t PerRecipeDelays::_internal_min_delays(int index) const {
  return _impl_.min_delays_.Get(index);
}
inline int32_t PerRecipeDelays::min_delays(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.PerRecipeDelays.min_delays)
  return _internal_min_delays(index);
}
inline void PerRecipeDelays::set_min_delays(int index, int32_t value) {
  _impl_.min_delays_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.PerRecipeDelays.min_delays)
}
inline void PerRecipeDelays::_internal_add_min_delays(int32_t value) {
  _impl_.min_delays_.Add(value);
}
inline void PerRecipeDelays::add_min_delays(int32_t value) {
  _internal_add_min_delays(value);
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.PerRecipeDelays.min_delays)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
PerRecipeDelays::_internal_min_delays() const {
  return _impl_.min_delays_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
PerRecipeDelays::min_delays() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.PerRecipeDelays.min_delays)
  return _internal_min_delays();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
PerRecipeDelays::_internal_mutable_min_delays() {
  return &_impl_.min_delays_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
PerRecipeDelays::mutable_min_delays() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.PerRecipeDelays.min_delays)
  return _internal_mutable_min_delays();
}

// -------------------------------------------------------------------

// PerSuccessorDelays

// repeated .operations_research.scheduling.rcpsp.PerRecipeDelays recipe_delays = 1;
inline int PerSuccessorDelays::_internal_recipe_delays_size() const {
  return _impl_.recipe_delays_.size();
}
inline int PerSuccessorDelays::recipe_delays_size() const {
  return _internal_recipe_delays_size();
}
inline void PerSuccessorDelays::clear_recipe_delays() {
  _impl_.recipe_delays_.Clear();
}
inline ::operations_research::scheduling::rcpsp::PerRecipeDelays* PerSuccessorDelays::mutable_recipe_delays(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.scheduling.rcpsp.PerSuccessorDelays.recipe_delays)
  return _impl_.recipe_delays_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerRecipeDelays >*
PerSuccessorDelays::mutable_recipe_delays() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.PerSuccessorDelays.recipe_delays)
  return &_impl_.recipe_delays_;
}
inline const ::operations_research::scheduling::rcpsp::PerRecipeDelays& PerSuccessorDelays::_internal_recipe_delays(int index) const {
  return _impl_.recipe_delays_.Get(index);
}
inline const ::operations_research::scheduling::rcpsp::PerRecipeDelays& PerSuccessorDelays::recipe_delays(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.PerSuccessorDelays.recipe_delays)
  return _internal_recipe_delays(index);
}
inline ::operations_research::scheduling::rcpsp::PerRecipeDelays* PerSuccessorDelays::_internal_add_recipe_delays() {
  return _impl_.recipe_delays_.Add();
}
inline ::operations_research::scheduling::rcpsp::PerRecipeDelays* PerSuccessorDelays::add_recipe_delays() {
  ::operations_research::scheduling::rcpsp::PerRecipeDelays* _add = _internal_add_recipe_delays();
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.PerSuccessorDelays.recipe_delays)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerRecipeDelays >&
PerSuccessorDelays::recipe_delays() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.PerSuccessorDelays.recipe_delays)
  return _impl_.recipe_delays_;
}

// -------------------------------------------------------------------

// Task

// repeated int32 successors = 1;
inline int Task::_internal_successors_size() const {
  return _impl_.successors_.size();
}
inline int Task::successors_size() const {
  return _internal_successors_size();
}
inline void Task::clear_successors() {
  _impl_.successors_.Clear();
}
inline int32_t Task::_internal_successors(int index) const {
  return _impl_.successors_.Get(index);
}
inline int32_t Task::successors(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Task.successors)
  return _internal_successors(index);
}
inline void Task::set_successors(int index, int32_t value) {
  _impl_.successors_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.Task.successors)
}
inline void Task::_internal_add_successors(int32_t value) {
  _impl_.successors_.Add(value);
}
inline void Task::add_successors(int32_t value) {
  _internal_add_successors(value);
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.Task.successors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Task::_internal_successors() const {
  return _impl_.successors_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Task::successors() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.Task.successors)
  return _internal_successors();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Task::_internal_mutable_successors() {
  return &_impl_.successors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Task::mutable_successors() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.Task.successors)
  return _internal_mutable_successors();
}

// repeated .operations_research.scheduling.rcpsp.Recipe recipes = 2;
inline int Task::_internal_recipes_size() const {
  return _impl_.recipes_.size();
}
inline int Task::recipes_size() const {
  return _internal_recipes_size();
}
inline void Task::clear_recipes() {
  _impl_.recipes_.Clear();
}
inline ::operations_research::scheduling::rcpsp::Recipe* Task::mutable_recipes(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.scheduling.rcpsp.Task.recipes)
  return _impl_.recipes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Recipe >*
Task::mutable_recipes() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.Task.recipes)
  return &_impl_.recipes_;
}
inline const ::operations_research::scheduling::rcpsp::Recipe& Task::_internal_recipes(int index) const {
  return _impl_.recipes_.Get(index);
}
inline const ::operations_research::scheduling::rcpsp::Recipe& Task::recipes(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Task.recipes)
  return _internal_recipes(index);
}
inline ::operations_research::scheduling::rcpsp::Recipe* Task::_internal_add_recipes() {
  return _impl_.recipes_.Add();
}
inline ::operations_research::scheduling::rcpsp::Recipe* Task::add_recipes() {
  ::operations_research::scheduling::rcpsp::Recipe* _add = _internal_add_recipes();
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.Task.recipes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Recipe >&
Task::recipes() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.Task.recipes)
  return _impl_.recipes_;
}

// repeated .operations_research.scheduling.rcpsp.PerSuccessorDelays successor_delays = 3;
inline int Task::_internal_successor_delays_size() const {
  return _impl_.successor_delays_.size();
}
inline int Task::successor_delays_size() const {
  return _internal_successor_delays_size();
}
inline void Task::clear_successor_delays() {
  _impl_.successor_delays_.Clear();
}
inline ::operations_research::scheduling::rcpsp::PerSuccessorDelays* Task::mutable_successor_delays(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.scheduling.rcpsp.Task.successor_delays)
  return _impl_.successor_delays_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerSuccessorDelays >*
Task::mutable_successor_delays() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.Task.successor_delays)
  return &_impl_.successor_delays_;
}
inline const ::operations_research::scheduling::rcpsp::PerSuccessorDelays& Task::_internal_successor_delays(int index) const {
  return _impl_.successor_delays_.Get(index);
}
inline const ::operations_research::scheduling::rcpsp::PerSuccessorDelays& Task::successor_delays(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.Task.successor_delays)
  return _internal_successor_delays(index);
}
inline ::operations_research::scheduling::rcpsp::PerSuccessorDelays* Task::_internal_add_successor_delays() {
  return _impl_.successor_delays_.Add();
}
inline ::operations_research::scheduling::rcpsp::PerSuccessorDelays* Task::add_successor_delays() {
  ::operations_research::scheduling::rcpsp::PerSuccessorDelays* _add = _internal_add_successor_delays();
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.Task.successor_delays)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::PerSuccessorDelays >&
Task::successor_delays() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.Task.successor_delays)
  return _impl_.successor_delays_;
}

// -------------------------------------------------------------------

// RcpspProblem

// repeated .operations_research.scheduling.rcpsp.Resource resources = 1;
inline int RcpspProblem::_internal_resources_size() const {
  return _impl_.resources_.size();
}
inline int RcpspProblem::resources_size() const {
  return _internal_resources_size();
}
inline void RcpspProblem::clear_resources() {
  _impl_.resources_.Clear();
}
inline ::operations_research::scheduling::rcpsp::Resource* RcpspProblem::mutable_resources(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.scheduling.rcpsp.RcpspProblem.resources)
  return _impl_.resources_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Resource >*
RcpspProblem::mutable_resources() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.RcpspProblem.resources)
  return &_impl_.resources_;
}
inline const ::operations_research::scheduling::rcpsp::Resource& RcpspProblem::_internal_resources(int index) const {
  return _impl_.resources_.Get(index);
}
inline const ::operations_research::scheduling::rcpsp::Resource& RcpspProblem::resources(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.resources)
  return _internal_resources(index);
}
inline ::operations_research::scheduling::rcpsp::Resource* RcpspProblem::_internal_add_resources() {
  return _impl_.resources_.Add();
}
inline ::operations_research::scheduling::rcpsp::Resource* RcpspProblem::add_resources() {
  ::operations_research::scheduling::rcpsp::Resource* _add = _internal_add_resources();
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.RcpspProblem.resources)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Resource >&
RcpspProblem::resources() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.RcpspProblem.resources)
  return _impl_.resources_;
}

// repeated .operations_research.scheduling.rcpsp.Task tasks = 2;
inline int RcpspProblem::_internal_tasks_size() const {
  return _impl_.tasks_.size();
}
inline int RcpspProblem::tasks_size() const {
  return _internal_tasks_size();
}
inline void RcpspProblem::clear_tasks() {
  _impl_.tasks_.Clear();
}
inline ::operations_research::scheduling::rcpsp::Task* RcpspProblem::mutable_tasks(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.scheduling.rcpsp.RcpspProblem.tasks)
  return _impl_.tasks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Task >*
RcpspProblem::mutable_tasks() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.RcpspProblem.tasks)
  return &_impl_.tasks_;
}
inline const ::operations_research::scheduling::rcpsp::Task& RcpspProblem::_internal_tasks(int index) const {
  return _impl_.tasks_.Get(index);
}
inline const ::operations_research::scheduling::rcpsp::Task& RcpspProblem::tasks(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.tasks)
  return _internal_tasks(index);
}
inline ::operations_research::scheduling::rcpsp::Task* RcpspProblem::_internal_add_tasks() {
  return _impl_.tasks_.Add();
}
inline ::operations_research::scheduling::rcpsp::Task* RcpspProblem::add_tasks() {
  ::operations_research::scheduling::rcpsp::Task* _add = _internal_add_tasks();
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.RcpspProblem.tasks)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::operations_research::scheduling::rcpsp::Task >&
RcpspProblem::tasks() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.RcpspProblem.tasks)
  return _impl_.tasks_;
}

// bool is_consumer_producer = 3;
inline void RcpspProblem::clear_is_consumer_producer() {
  _impl_.is_consumer_producer_ = false;
}
inline bool RcpspProblem::_internal_is_consumer_producer() const {
  return _impl_.is_consumer_producer_;
}
inline bool RcpspProblem::is_consumer_producer() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.is_consumer_producer)
  return _internal_is_consumer_producer();
}
inline void RcpspProblem::_internal_set_is_consumer_producer(bool value) {
  
  _impl_.is_consumer_producer_ = value;
}
inline void RcpspProblem::set_is_consumer_producer(bool value) {
  _internal_set_is_consumer_producer(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.is_consumer_producer)
}

// bool is_resource_investment = 4;
inline void RcpspProblem::clear_is_resource_investment() {
  _impl_.is_resource_investment_ = false;
}
inline bool RcpspProblem::_internal_is_resource_investment() const {
  return _impl_.is_resource_investment_;
}
inline bool RcpspProblem::is_resource_investment() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.is_resource_investment)
  return _internal_is_resource_investment();
}
inline void RcpspProblem::_internal_set_is_resource_investment(bool value) {
  
  _impl_.is_resource_investment_ = value;
}
inline void RcpspProblem::set_is_resource_investment(bool value) {
  _internal_set_is_resource_investment(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.is_resource_investment)
}

// bool is_rcpsp_max = 5;
inline void RcpspProblem::clear_is_rcpsp_max() {
  _impl_.is_rcpsp_max_ = false;
}
inline bool RcpspProblem::_internal_is_rcpsp_max() const {
  return _impl_.is_rcpsp_max_;
}
inline bool RcpspProblem::is_rcpsp_max() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.is_rcpsp_max)
  return _internal_is_rcpsp_max();
}
inline void RcpspProblem::_internal_set_is_rcpsp_max(bool value) {
  
  _impl_.is_rcpsp_max_ = value;
}
inline void RcpspProblem::set_is_rcpsp_max(bool value) {
  _internal_set_is_rcpsp_max(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.is_rcpsp_max)
}

// int32 deadline = 6;
inline void RcpspProblem::clear_deadline() {
  _impl_.deadline_ = 0;
}
inline int32_t RcpspProblem::_internal_deadline() const {
  return _impl_.deadline_;
}
inline int32_t RcpspProblem::deadline() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.deadline)
  return _internal_deadline();
}
inline void RcpspProblem::_internal_set_deadline(int32_t value) {
  
  _impl_.deadline_ = value;
}
inline void RcpspProblem::set_deadline(int32_t value) {
  _internal_set_deadline(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.deadline)
}

// int32 horizon = 7;
inline void RcpspProblem::clear_horizon() {
  _impl_.horizon_ = 0;
}
inline int32_t RcpspProblem::_internal_horizon() const {
  return _impl_.horizon_;
}
inline int32_t RcpspProblem::horizon() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.horizon)
  return _internal_horizon();
}
inline void RcpspProblem::_internal_set_horizon(int32_t value) {
  
  _impl_.horizon_ = value;
}
inline void RcpspProblem::set_horizon(int32_t value) {
  _internal_set_horizon(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.horizon)
}

// int32 release_date = 8;
inline void RcpspProblem::clear_release_date() {
  _impl_.release_date_ = 0;
}
inline int32_t RcpspProblem::_internal_release_date() const {
  return _impl_.release_date_;
}
inline int32_t RcpspProblem::release_date() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.release_date)
  return _internal_release_date();
}
inline void RcpspProblem::_internal_set_release_date(int32_t value) {
  
  _impl_.release_date_ = value;
}
inline void RcpspProblem::set_release_date(int32_t value) {
  _internal_set_release_date(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.release_date)
}

// int32 tardiness_cost = 9;
inline void RcpspProblem::clear_tardiness_cost() {
  _impl_.tardiness_cost_ = 0;
}
inline int32_t RcpspProblem::_internal_tardiness_cost() const {
  return _impl_.tardiness_cost_;
}
inline int32_t RcpspProblem::tardiness_cost() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.tardiness_cost)
  return _internal_tardiness_cost();
}
inline void RcpspProblem::_internal_set_tardiness_cost(int32_t value) {
  
  _impl_.tardiness_cost_ = value;
}
inline void RcpspProblem::set_tardiness_cost(int32_t value) {
  _internal_set_tardiness_cost(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.tardiness_cost)
}

// int32 mpm_time = 10;
inline void RcpspProblem::clear_mpm_time() {
  _impl_.mpm_time_ = 0;
}
inline int32_t RcpspProblem::_internal_mpm_time() const {
  return _impl_.mpm_time_;
}
inline int32_t RcpspProblem::mpm_time() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.mpm_time)
  return _internal_mpm_time();
}
inline void RcpspProblem::_internal_set_mpm_time(int32_t value) {
  
  _impl_.mpm_time_ = value;
}
inline void RcpspProblem::set_mpm_time(int32_t value) {
  _internal_set_mpm_time(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.mpm_time)
}

// int64 seed = 11;
inline void RcpspProblem::clear_seed() {
  _impl_.seed_ = int64_t{0};
}
inline int64_t RcpspProblem::_internal_seed() const {
  return _impl_.seed_;
}
inline int64_t RcpspProblem::seed() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.seed)
  return _internal_seed();
}
inline void RcpspProblem::_internal_set_seed(int64_t value) {
  
  _impl_.seed_ = value;
}
inline void RcpspProblem::set_seed(int64_t value) {
  _internal_set_seed(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.seed)
}

// string basedata = 12;
inline void RcpspProblem::clear_basedata() {
  _impl_.basedata_.ClearToEmpty();
}
inline const std::string& RcpspProblem::basedata() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.basedata)
  return _internal_basedata();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RcpspProblem::set_basedata(ArgT0&& arg0, ArgT... args) {
 
 _impl_.basedata_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.basedata)
}
inline std::string* RcpspProblem::mutable_basedata() {
  std::string* _s = _internal_mutable_basedata();
  // @@protoc_insertion_point(field_mutable:operations_research.scheduling.rcpsp.RcpspProblem.basedata)
  return _s;
}
inline const std::string& RcpspProblem::_internal_basedata() const {
  return _impl_.basedata_.Get();
}
inline void RcpspProblem::_internal_set_basedata(const std::string& value) {
  
  _impl_.basedata_.Set(value, GetArenaForAllocation());
}
inline std::string* RcpspProblem::_internal_mutable_basedata() {
  
  return _impl_.basedata_.Mutable(GetArenaForAllocation());
}
inline std::string* RcpspProblem::release_basedata() {
  // @@protoc_insertion_point(field_release:operations_research.scheduling.rcpsp.RcpspProblem.basedata)
  return _impl_.basedata_.Release();
}
inline void RcpspProblem::set_allocated_basedata(std::string* basedata) {
  if (basedata != nullptr) {
    
  } else {
    
  }
  _impl_.basedata_.SetAllocated(basedata, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.basedata_.IsDefault()) {
    _impl_.basedata_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:operations_research.scheduling.rcpsp.RcpspProblem.basedata)
}

// int32 due_date = 13;
inline void RcpspProblem::clear_due_date() {
  _impl_.due_date_ = 0;
}
inline int32_t RcpspProblem::_internal_due_date() const {
  return _impl_.due_date_;
}
inline int32_t RcpspProblem::due_date() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.due_date)
  return _internal_due_date();
}
inline void RcpspProblem::_internal_set_due_date(int32_t value) {
  
  _impl_.due_date_ = value;
}
inline void RcpspProblem::set_due_date(int32_t value) {
  _internal_set_due_date(value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.due_date)
}

// string name = 14;
inline void RcpspProblem::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& RcpspProblem::name() const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspProblem.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RcpspProblem::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspProblem.name)
}
inline std::string* RcpspProblem::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:operations_research.scheduling.rcpsp.RcpspProblem.name)
  return _s;
}
inline const std::string& RcpspProblem::_internal_name() const {
  return _impl_.name_.Get();
}
inline void RcpspProblem::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* RcpspProblem::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* RcpspProblem::release_name() {
  // @@protoc_insertion_point(field_release:operations_research.scheduling.rcpsp.RcpspProblem.name)
  return _impl_.name_.Release();
}
inline void RcpspProblem::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:operations_research.scheduling.rcpsp.RcpspProblem.name)
}

// -------------------------------------------------------------------

// RcpspAssignment

// repeated int64 start_of_task = 1;
inline int RcpspAssignment::_internal_start_of_task_size() const {
  return _impl_.start_of_task_.size();
}
inline int RcpspAssignment::start_of_task_size() const {
  return _internal_start_of_task_size();
}
inline void RcpspAssignment::clear_start_of_task() {
  _impl_.start_of_task_.Clear();
}
inline int64_t RcpspAssignment::_internal_start_of_task(int index) const {
  return _impl_.start_of_task_.Get(index);
}
inline int64_t RcpspAssignment::start_of_task(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspAssignment.start_of_task)
  return _internal_start_of_task(index);
}
inline void RcpspAssignment::set_start_of_task(int index, int64_t value) {
  _impl_.start_of_task_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspAssignment.start_of_task)
}
inline void RcpspAssignment::_internal_add_start_of_task(int64_t value) {
  _impl_.start_of_task_.Add(value);
}
inline void RcpspAssignment::add_start_of_task(int64_t value) {
  _internal_add_start_of_task(value);
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.RcpspAssignment.start_of_task)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
RcpspAssignment::_internal_start_of_task() const {
  return _impl_.start_of_task_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
RcpspAssignment::start_of_task() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.RcpspAssignment.start_of_task)
  return _internal_start_of_task();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
RcpspAssignment::_internal_mutable_start_of_task() {
  return &_impl_.start_of_task_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
RcpspAssignment::mutable_start_of_task() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.RcpspAssignment.start_of_task)
  return _internal_mutable_start_of_task();
}

// repeated int32 selected_recipe_of_task = 2;
inline int RcpspAssignment::_internal_selected_recipe_of_task_size() const {
  return _impl_.selected_recipe_of_task_.size();
}
inline int RcpspAssignment::selected_recipe_of_task_size() const {
  return _internal_selected_recipe_of_task_size();
}
inline void RcpspAssignment::clear_selected_recipe_of_task() {
  _impl_.selected_recipe_of_task_.Clear();
}
inline int32_t RcpspAssignment::_internal_selected_recipe_of_task(int index) const {
  return _impl_.selected_recipe_of_task_.Get(index);
}
inline int32_t RcpspAssignment::selected_recipe_of_task(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.scheduling.rcpsp.RcpspAssignment.selected_recipe_of_task)
  return _internal_selected_recipe_of_task(index);
}
inline void RcpspAssignment::set_selected_recipe_of_task(int index, int32_t value) {
  _impl_.selected_recipe_of_task_.Set(index, value);
  // @@protoc_insertion_point(field_set:operations_research.scheduling.rcpsp.RcpspAssignment.selected_recipe_of_task)
}
inline void RcpspAssignment::_internal_add_selected_recipe_of_task(int32_t value) {
  _impl_.selected_recipe_of_task_.Add(value);
}
inline void RcpspAssignment::add_selected_recipe_of_task(int32_t value) {
  _internal_add_selected_recipe_of_task(value);
  // @@protoc_insertion_point(field_add:operations_research.scheduling.rcpsp.RcpspAssignment.selected_recipe_of_task)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
RcpspAssignment::_internal_selected_recipe_of_task() const {
  return _impl_.selected_recipe_of_task_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
RcpspAssignment::selected_recipe_of_task() const {
  // @@protoc_insertion_point(field_list:operations_research.scheduling.rcpsp.RcpspAssignment.selected_recipe_of_task)
  return _internal_selected_recipe_of_task();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
RcpspAssignment::_internal_mutable_selected_recipe_of_task() {
  return &_impl_.selected_recipe_of_task_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
RcpspAssignment::mutable_selected_recipe_of_task() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.scheduling.rcpsp.RcpspAssignment.selected_recipe_of_task)
  return _internal_mutable_selected_recipe_of_task();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rcpsp
}  // namespace scheduling
}  // namespace operations_research

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ortools_2fscheduling_2frcpsp_2eproto
