// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/bop/bop_parameters.proto

#ifndef PROTOBUF_INCLUDED_ortools_2fbop_2fbop_5fparameters_2eproto
#define PROTOBUF_INCLUDED_ortools_2fbop_2fbop_5fparameters_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ortools_2fbop_2fbop_5fparameters_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ortools_2fbop_2fbop_5fparameters_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ortools_2fbop_2fbop_5fparameters_2eproto();
namespace operations_research {
namespace bop {
class BopOptimizerMethod;
class BopOptimizerMethodDefaultTypeInternal;
extern BopOptimizerMethodDefaultTypeInternal _BopOptimizerMethod_default_instance_;
class BopParameters;
class BopParametersDefaultTypeInternal;
extern BopParametersDefaultTypeInternal _BopParameters_default_instance_;
class BopSolverOptimizerSet;
class BopSolverOptimizerSetDefaultTypeInternal;
extern BopSolverOptimizerSetDefaultTypeInternal _BopSolverOptimizerSet_default_instance_;
}  // namespace bop
}  // namespace operations_research
namespace google {
namespace protobuf {
template<> ::operations_research::bop::BopOptimizerMethod* Arena::CreateMaybeMessage<::operations_research::bop::BopOptimizerMethod>(Arena*);
template<> ::operations_research::bop::BopParameters* Arena::CreateMaybeMessage<::operations_research::bop::BopParameters>(Arena*);
template<> ::operations_research::bop::BopSolverOptimizerSet* Arena::CreateMaybeMessage<::operations_research::bop::BopSolverOptimizerSet>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace operations_research {
namespace bop {

enum BopOptimizerMethod_OptimizerType {
  BopOptimizerMethod_OptimizerType_SAT_CORE_BASED = 0,
  BopOptimizerMethod_OptimizerType_SAT_LINEAR_SEARCH = 15,
  BopOptimizerMethod_OptimizerType_LINEAR_RELAXATION = 1,
  BopOptimizerMethod_OptimizerType_LOCAL_SEARCH = 2,
  BopOptimizerMethod_OptimizerType_RANDOM_FIRST_SOLUTION = 3,
  BopOptimizerMethod_OptimizerType_RANDOM_CONSTRAINT_LNS = 4,
  BopOptimizerMethod_OptimizerType_RANDOM_VARIABLE_LNS = 5,
  BopOptimizerMethod_OptimizerType_COMPLETE_LNS = 7,
  BopOptimizerMethod_OptimizerType_LP_FIRST_SOLUTION = 8,
  BopOptimizerMethod_OptimizerType_OBJECTIVE_FIRST_SOLUTION = 9,
  BopOptimizerMethod_OptimizerType_USER_GUIDED_FIRST_SOLUTION = 14,
  BopOptimizerMethod_OptimizerType_RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP = 11,
  BopOptimizerMethod_OptimizerType_RANDOM_VARIABLE_LNS_GUIDED_BY_LP = 12,
  BopOptimizerMethod_OptimizerType_RELATION_GRAPH_LNS = 16,
  BopOptimizerMethod_OptimizerType_RELATION_GRAPH_LNS_GUIDED_BY_LP = 17
};
bool BopOptimizerMethod_OptimizerType_IsValid(int value);
const BopOptimizerMethod_OptimizerType BopOptimizerMethod_OptimizerType_OptimizerType_MIN = BopOptimizerMethod_OptimizerType_SAT_CORE_BASED;
const BopOptimizerMethod_OptimizerType BopOptimizerMethod_OptimizerType_OptimizerType_MAX = BopOptimizerMethod_OptimizerType_RELATION_GRAPH_LNS_GUIDED_BY_LP;
const int BopOptimizerMethod_OptimizerType_OptimizerType_ARRAYSIZE = BopOptimizerMethod_OptimizerType_OptimizerType_MAX + 1;

const ::google::protobuf::EnumDescriptor* BopOptimizerMethod_OptimizerType_descriptor();
inline const ::std::string& BopOptimizerMethod_OptimizerType_Name(BopOptimizerMethod_OptimizerType value) {
  return ::google::protobuf::internal::NameOfEnum(
    BopOptimizerMethod_OptimizerType_descriptor(), value);
}
inline bool BopOptimizerMethod_OptimizerType_Parse(
    const ::std::string& name, BopOptimizerMethod_OptimizerType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BopOptimizerMethod_OptimizerType>(
    BopOptimizerMethod_OptimizerType_descriptor(), name, value);
}
enum BopParameters_ThreadSynchronizationType {
  BopParameters_ThreadSynchronizationType_NO_SYNCHRONIZATION = 0,
  BopParameters_ThreadSynchronizationType_SYNCHRONIZE_ALL = 1,
  BopParameters_ThreadSynchronizationType_SYNCHRONIZE_ON_RIGHT = 2
};
bool BopParameters_ThreadSynchronizationType_IsValid(int value);
const BopParameters_ThreadSynchronizationType BopParameters_ThreadSynchronizationType_ThreadSynchronizationType_MIN = BopParameters_ThreadSynchronizationType_NO_SYNCHRONIZATION;
const BopParameters_ThreadSynchronizationType BopParameters_ThreadSynchronizationType_ThreadSynchronizationType_MAX = BopParameters_ThreadSynchronizationType_SYNCHRONIZE_ON_RIGHT;
const int BopParameters_ThreadSynchronizationType_ThreadSynchronizationType_ARRAYSIZE = BopParameters_ThreadSynchronizationType_ThreadSynchronizationType_MAX + 1;

const ::google::protobuf::EnumDescriptor* BopParameters_ThreadSynchronizationType_descriptor();
inline const ::std::string& BopParameters_ThreadSynchronizationType_Name(BopParameters_ThreadSynchronizationType value) {
  return ::google::protobuf::internal::NameOfEnum(
    BopParameters_ThreadSynchronizationType_descriptor(), value);
}
inline bool BopParameters_ThreadSynchronizationType_Parse(
    const ::std::string& name, BopParameters_ThreadSynchronizationType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BopParameters_ThreadSynchronizationType>(
    BopParameters_ThreadSynchronizationType_descriptor(), name, value);
}
// ===================================================================

class BopOptimizerMethod :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.bop.BopOptimizerMethod) */ {
 public:
  BopOptimizerMethod();
  virtual ~BopOptimizerMethod();

  BopOptimizerMethod(const BopOptimizerMethod& from);

  inline BopOptimizerMethod& operator=(const BopOptimizerMethod& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BopOptimizerMethod(BopOptimizerMethod&& from) noexcept
    : BopOptimizerMethod() {
    *this = ::std::move(from);
  }

  inline BopOptimizerMethod& operator=(BopOptimizerMethod&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const BopOptimizerMethod& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BopOptimizerMethod* internal_default_instance() {
    return reinterpret_cast<const BopOptimizerMethod*>(
               &_BopOptimizerMethod_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BopOptimizerMethod* other);
  friend void swap(BopOptimizerMethod& a, BopOptimizerMethod& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BopOptimizerMethod* New() const final {
    return CreateMaybeMessage<BopOptimizerMethod>(nullptr);
  }

  BopOptimizerMethod* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BopOptimizerMethod>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BopOptimizerMethod& from);
  void MergeFrom(const BopOptimizerMethod& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BopOptimizerMethod* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef BopOptimizerMethod_OptimizerType OptimizerType;
  static const OptimizerType SAT_CORE_BASED =
    BopOptimizerMethod_OptimizerType_SAT_CORE_BASED;
  static const OptimizerType SAT_LINEAR_SEARCH =
    BopOptimizerMethod_OptimizerType_SAT_LINEAR_SEARCH;
  static const OptimizerType LINEAR_RELAXATION =
    BopOptimizerMethod_OptimizerType_LINEAR_RELAXATION;
  static const OptimizerType LOCAL_SEARCH =
    BopOptimizerMethod_OptimizerType_LOCAL_SEARCH;
  static const OptimizerType RANDOM_FIRST_SOLUTION =
    BopOptimizerMethod_OptimizerType_RANDOM_FIRST_SOLUTION;
  static const OptimizerType RANDOM_CONSTRAINT_LNS =
    BopOptimizerMethod_OptimizerType_RANDOM_CONSTRAINT_LNS;
  static const OptimizerType RANDOM_VARIABLE_LNS =
    BopOptimizerMethod_OptimizerType_RANDOM_VARIABLE_LNS;
  static const OptimizerType COMPLETE_LNS =
    BopOptimizerMethod_OptimizerType_COMPLETE_LNS;
  static const OptimizerType LP_FIRST_SOLUTION =
    BopOptimizerMethod_OptimizerType_LP_FIRST_SOLUTION;
  static const OptimizerType OBJECTIVE_FIRST_SOLUTION =
    BopOptimizerMethod_OptimizerType_OBJECTIVE_FIRST_SOLUTION;
  static const OptimizerType USER_GUIDED_FIRST_SOLUTION =
    BopOptimizerMethod_OptimizerType_USER_GUIDED_FIRST_SOLUTION;
  static const OptimizerType RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP =
    BopOptimizerMethod_OptimizerType_RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP;
  static const OptimizerType RANDOM_VARIABLE_LNS_GUIDED_BY_LP =
    BopOptimizerMethod_OptimizerType_RANDOM_VARIABLE_LNS_GUIDED_BY_LP;
  static const OptimizerType RELATION_GRAPH_LNS =
    BopOptimizerMethod_OptimizerType_RELATION_GRAPH_LNS;
  static const OptimizerType RELATION_GRAPH_LNS_GUIDED_BY_LP =
    BopOptimizerMethod_OptimizerType_RELATION_GRAPH_LNS_GUIDED_BY_LP;
  static inline bool OptimizerType_IsValid(int value) {
    return BopOptimizerMethod_OptimizerType_IsValid(value);
  }
  static const OptimizerType OptimizerType_MIN =
    BopOptimizerMethod_OptimizerType_OptimizerType_MIN;
  static const OptimizerType OptimizerType_MAX =
    BopOptimizerMethod_OptimizerType_OptimizerType_MAX;
  static const int OptimizerType_ARRAYSIZE =
    BopOptimizerMethod_OptimizerType_OptimizerType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  OptimizerType_descriptor() {
    return BopOptimizerMethod_OptimizerType_descriptor();
  }
  static inline const ::std::string& OptimizerType_Name(OptimizerType value) {
    return BopOptimizerMethod_OptimizerType_Name(value);
  }
  static inline bool OptimizerType_Parse(const ::std::string& name,
      OptimizerType* value) {
    return BopOptimizerMethod_OptimizerType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .operations_research.bop.BopOptimizerMethod.OptimizerType type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::operations_research::bop::BopOptimizerMethod_OptimizerType type() const;
  void set_type(::operations_research::bop::BopOptimizerMethod_OptimizerType value);

  // @@protoc_insertion_point(class_scope:operations_research.bop.BopOptimizerMethod)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  int type_;
  friend struct ::TableStruct_ortools_2fbop_2fbop_5fparameters_2eproto;
};
// -------------------------------------------------------------------

class BopSolverOptimizerSet :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.bop.BopSolverOptimizerSet) */ {
 public:
  BopSolverOptimizerSet();
  virtual ~BopSolverOptimizerSet();

  BopSolverOptimizerSet(const BopSolverOptimizerSet& from);

  inline BopSolverOptimizerSet& operator=(const BopSolverOptimizerSet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BopSolverOptimizerSet(BopSolverOptimizerSet&& from) noexcept
    : BopSolverOptimizerSet() {
    *this = ::std::move(from);
  }

  inline BopSolverOptimizerSet& operator=(BopSolverOptimizerSet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const BopSolverOptimizerSet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BopSolverOptimizerSet* internal_default_instance() {
    return reinterpret_cast<const BopSolverOptimizerSet*>(
               &_BopSolverOptimizerSet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(BopSolverOptimizerSet* other);
  friend void swap(BopSolverOptimizerSet& a, BopSolverOptimizerSet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BopSolverOptimizerSet* New() const final {
    return CreateMaybeMessage<BopSolverOptimizerSet>(nullptr);
  }

  BopSolverOptimizerSet* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BopSolverOptimizerSet>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BopSolverOptimizerSet& from);
  void MergeFrom(const BopSolverOptimizerSet& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BopSolverOptimizerSet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .operations_research.bop.BopOptimizerMethod methods = 1;
  int methods_size() const;
  void clear_methods();
  static const int kMethodsFieldNumber = 1;
  ::operations_research::bop::BopOptimizerMethod* mutable_methods(int index);
  ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopOptimizerMethod >*
      mutable_methods();
  const ::operations_research::bop::BopOptimizerMethod& methods(int index) const;
  ::operations_research::bop::BopOptimizerMethod* add_methods();
  const ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopOptimizerMethod >&
      methods() const;

  // @@protoc_insertion_point(class_scope:operations_research.bop.BopSolverOptimizerSet)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopOptimizerMethod > methods_;
  friend struct ::TableStruct_ortools_2fbop_2fbop_5fparameters_2eproto;
};
// -------------------------------------------------------------------

class BopParameters :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.bop.BopParameters) */ {
 public:
  BopParameters();
  virtual ~BopParameters();

  BopParameters(const BopParameters& from);

  inline BopParameters& operator=(const BopParameters& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BopParameters(BopParameters&& from) noexcept
    : BopParameters() {
    *this = ::std::move(from);
  }

  inline BopParameters& operator=(BopParameters&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const BopParameters& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BopParameters* internal_default_instance() {
    return reinterpret_cast<const BopParameters*>(
               &_BopParameters_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(BopParameters* other);
  friend void swap(BopParameters& a, BopParameters& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BopParameters* New() const final {
    return CreateMaybeMessage<BopParameters>(nullptr);
  }

  BopParameters* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BopParameters>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BopParameters& from);
  void MergeFrom(const BopParameters& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BopParameters* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef BopParameters_ThreadSynchronizationType ThreadSynchronizationType;
  static const ThreadSynchronizationType NO_SYNCHRONIZATION =
    BopParameters_ThreadSynchronizationType_NO_SYNCHRONIZATION;
  static const ThreadSynchronizationType SYNCHRONIZE_ALL =
    BopParameters_ThreadSynchronizationType_SYNCHRONIZE_ALL;
  static const ThreadSynchronizationType SYNCHRONIZE_ON_RIGHT =
    BopParameters_ThreadSynchronizationType_SYNCHRONIZE_ON_RIGHT;
  static inline bool ThreadSynchronizationType_IsValid(int value) {
    return BopParameters_ThreadSynchronizationType_IsValid(value);
  }
  static const ThreadSynchronizationType ThreadSynchronizationType_MIN =
    BopParameters_ThreadSynchronizationType_ThreadSynchronizationType_MIN;
  static const ThreadSynchronizationType ThreadSynchronizationType_MAX =
    BopParameters_ThreadSynchronizationType_ThreadSynchronizationType_MAX;
  static const int ThreadSynchronizationType_ARRAYSIZE =
    BopParameters_ThreadSynchronizationType_ThreadSynchronizationType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ThreadSynchronizationType_descriptor() {
    return BopParameters_ThreadSynchronizationType_descriptor();
  }
  static inline const ::std::string& ThreadSynchronizationType_Name(ThreadSynchronizationType value) {
    return BopParameters_ThreadSynchronizationType_Name(value);
  }
  static inline bool ThreadSynchronizationType_Parse(const ::std::string& name,
      ThreadSynchronizationType* value) {
    return BopParameters_ThreadSynchronizationType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .operations_research.bop.BopSolverOptimizerSet solver_optimizer_sets = 26;
  int solver_optimizer_sets_size() const;
  void clear_solver_optimizer_sets();
  static const int kSolverOptimizerSetsFieldNumber = 26;
  ::operations_research::bop::BopSolverOptimizerSet* mutable_solver_optimizer_sets(int index);
  ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopSolverOptimizerSet >*
      mutable_solver_optimizer_sets();
  const ::operations_research::bop::BopSolverOptimizerSet& solver_optimizer_sets(int index) const;
  ::operations_research::bop::BopSolverOptimizerSet* add_solver_optimizer_sets();
  const ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopSolverOptimizerSet >&
      solver_optimizer_sets() const;

  // optional string default_solver_optimizer_sets = 33 [default = "methods:{type:LOCAL_SEARCH }                       methods:{type:RANDOM_FIRST_SOLUTION }              methods:{type:LINEAR_RELAXATION }                  methods:{type:LP_FIRST_SOLUTION }                  methods:{type:OBJECTIVE_FIRST_SOLUTION }           methods:{type:USER_GUIDED_FIRST_SOLUTION }         methods:{type:RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP } methods:{type:RANDOM_VARIABLE_LNS_GUIDED_BY_LP }   methods:{type:RELATION_GRAPH_LNS }                 methods:{type:RELATION_GRAPH_LNS_GUIDED_BY_LP }    methods:{type:RANDOM_CONSTRAINT_LNS }              methods:{type:RANDOM_VARIABLE_LNS }                methods:{type:SAT_CORE_BASED }                     methods:{type:COMPLETE_LNS }                       "];
  bool has_default_solver_optimizer_sets() const;
  void clear_default_solver_optimizer_sets();
  static const int kDefaultSolverOptimizerSetsFieldNumber = 33;
  const ::std::string& default_solver_optimizer_sets() const;
  void set_default_solver_optimizer_sets(const ::std::string& value);
  #if LANG_CXX11
  void set_default_solver_optimizer_sets(::std::string&& value);
  #endif
  void set_default_solver_optimizer_sets(const char* value);
  void set_default_solver_optimizer_sets(const char* value, size_t size);
  ::std::string* mutable_default_solver_optimizer_sets();
  ::std::string* release_default_solver_optimizer_sets();
  void set_allocated_default_solver_optimizer_sets(::std::string* default_solver_optimizer_sets);

  // optional bool log_search_progress = 14 [default = false];
  bool has_log_search_progress() const;
  void clear_log_search_progress();
  static const int kLogSearchProgressFieldNumber = 14;
  bool log_search_progress() const;
  void set_log_search_progress(bool value);

  // optional bool prune_search_tree = 4 [default = false];
  bool has_prune_search_tree() const;
  void clear_prune_search_tree();
  static const int kPruneSearchTreeFieldNumber = 4;
  bool prune_search_tree() const;
  void set_prune_search_tree(bool value);

  // optional bool sort_constraints_by_num_terms = 5 [default = false];
  bool has_sort_constraints_by_num_terms() const;
  void clear_sort_constraints_by_num_terms();
  static const int kSortConstraintsByNumTermsFieldNumber = 5;
  bool sort_constraints_by_num_terms() const;
  void set_sort_constraints_by_num_terms(bool value);

  // optional bool use_symmetry = 17 [default = false];
  bool has_use_symmetry() const;
  void clear_use_symmetry();
  static const int kUseSymmetryFieldNumber = 17;
  bool use_symmetry() const;
  void set_use_symmetry(bool value);

  // optional .operations_research.bop.BopParameters.ThreadSynchronizationType synchronization_type = 25 [default = NO_SYNCHRONIZATION];
  bool has_synchronization_type() const;
  void clear_synchronization_type();
  static const int kSynchronizationTypeFieldNumber = 25;
  ::operations_research::bop::BopParameters_ThreadSynchronizationType synchronization_type() const;
  void set_synchronization_type(::operations_research::bop::BopParameters_ThreadSynchronizationType value);

  // optional int32 max_number_of_consecutive_failing_optimizer_calls = 35;
  bool has_max_number_of_consecutive_failing_optimizer_calls() const;
  void clear_max_number_of_consecutive_failing_optimizer_calls();
  static const int kMaxNumberOfConsecutiveFailingOptimizerCallsFieldNumber = 35;
  ::google::protobuf::int32 max_number_of_consecutive_failing_optimizer_calls() const;
  void set_max_number_of_consecutive_failing_optimizer_calls(::google::protobuf::int32 value);

  // optional bool exploit_symmetry_in_sat_first_solution = 40 [default = false];
  bool has_exploit_symmetry_in_sat_first_solution() const;
  void clear_exploit_symmetry_in_sat_first_solution();
  static const int kExploitSymmetryInSatFirstSolutionFieldNumber = 40;
  bool exploit_symmetry_in_sat_first_solution() const;
  void set_exploit_symmetry_in_sat_first_solution(bool value);

  // optional bool use_potential_one_flip_repairs_in_ls = 39 [default = false];
  bool has_use_potential_one_flip_repairs_in_ls() const;
  void clear_use_potential_one_flip_repairs_in_ls();
  static const int kUsePotentialOneFlipRepairsInLsFieldNumber = 39;
  bool use_potential_one_flip_repairs_in_ls() const;
  void set_use_potential_one_flip_repairs_in_ls(bool value);

  // optional bool use_lp_strong_branching = 29 [default = false];
  bool has_use_lp_strong_branching() const;
  void clear_use_lp_strong_branching();
  static const int kUseLpStrongBranchingFieldNumber = 29;
  bool use_lp_strong_branching() const;
  void set_use_lp_strong_branching(bool value);

  // optional double decomposed_problem_min_time_in_seconds = 36 [default = 0];
  bool has_decomposed_problem_min_time_in_seconds() const;
  void clear_decomposed_problem_min_time_in_seconds();
  static const int kDecomposedProblemMinTimeInSecondsFieldNumber = 36;
  double decomposed_problem_min_time_in_seconds() const;
  void set_decomposed_problem_min_time_in_seconds(double value);

  // optional int32 max_lp_solve_for_feasibility_problems = 41 [default = 0];
  bool has_max_lp_solve_for_feasibility_problems() const;
  void clear_max_lp_solve_for_feasibility_problems();
  static const int kMaxLpSolveForFeasibilityProblemsFieldNumber = 41;
  ::google::protobuf::int32 max_lp_solve_for_feasibility_problems() const;
  void set_max_lp_solve_for_feasibility_problems(::google::protobuf::int32 value);

  // optional double max_time_in_seconds = 1 [default = inf];
  bool has_max_time_in_seconds() const;
  void clear_max_time_in_seconds();
  static const int kMaxTimeInSecondsFieldNumber = 1;
  double max_time_in_seconds() const;
  void set_max_time_in_seconds(double value);

  // optional int32 max_num_decisions_in_ls = 2 [default = 4];
  bool has_max_num_decisions_in_ls() const;
  void clear_max_num_decisions_in_ls();
  static const int kMaxNumDecisionsInLsFieldNumber = 2;
  ::google::protobuf::int32 max_num_decisions_in_ls() const;
  void set_max_num_decisions_in_ls(::google::protobuf::int32 value);

  // optional int32 random_seed = 7 [default = 8];
  bool has_random_seed() const;
  void clear_random_seed();
  static const int kRandomSeedFieldNumber = 7;
  ::google::protobuf::int32 random_seed() const;
  void set_random_seed(::google::protobuf::int32 value);

  // optional int32 num_relaxed_vars = 8 [default = 10];
  bool has_num_relaxed_vars() const;
  void clear_num_relaxed_vars();
  static const int kNumRelaxedVarsFieldNumber = 8;
  ::google::protobuf::int32 num_relaxed_vars() const;
  void set_num_relaxed_vars(::google::protobuf::int32 value);

  // optional int32 max_number_of_conflicts_in_random_lns = 9 [default = 2500];
  bool has_max_number_of_conflicts_in_random_lns() const;
  void clear_max_number_of_conflicts_in_random_lns();
  static const int kMaxNumberOfConflictsInRandomLnsFieldNumber = 9;
  ::google::protobuf::int32 max_number_of_conflicts_in_random_lns() const;
  void set_max_number_of_conflicts_in_random_lns(::google::protobuf::int32 value);

  // optional bool compute_estimated_impact = 3 [default = true];
  bool has_compute_estimated_impact() const;
  void clear_compute_estimated_impact();
  static const int kComputeEstimatedImpactFieldNumber = 3;
  bool compute_estimated_impact() const;
  void set_compute_estimated_impact(bool value);

  // optional bool use_random_lns = 6 [default = true];
  bool has_use_random_lns() const;
  void clear_use_random_lns();
  static const int kUseRandomLnsFieldNumber = 6;
  bool use_random_lns() const;
  void set_use_random_lns(bool value);

  // optional bool use_lp_lns = 12 [default = true];
  bool has_use_lp_lns() const;
  void clear_use_lp_lns();
  static const int kUseLpLnsFieldNumber = 12;
  bool use_lp_lns() const;
  void set_use_lp_lns(bool value);

  // optional bool use_sat_to_choose_lns_neighbourhood = 15 [default = true];
  bool has_use_sat_to_choose_lns_neighbourhood() const;
  void clear_use_sat_to_choose_lns_neighbourhood();
  static const int kUseSatToChooseLnsNeighbourhoodFieldNumber = 15;
  bool use_sat_to_choose_lns_neighbourhood() const;
  void set_use_sat_to_choose_lns_neighbourhood(bool value);

  // optional int32 num_random_lns_tries = 10 [default = 1];
  bool has_num_random_lns_tries() const;
  void clear_num_random_lns_tries();
  static const int kNumRandomLnsTriesFieldNumber = 10;
  ::google::protobuf::int32 num_random_lns_tries() const;
  void set_num_random_lns_tries(::google::protobuf::int32 value);

  // optional int64 max_number_of_backtracks_in_ls = 11 [default = 100000000];
  bool has_max_number_of_backtracks_in_ls() const;
  void clear_max_number_of_backtracks_in_ls();
  static const int kMaxNumberOfBacktracksInLsFieldNumber = 11;
  ::google::protobuf::int64 max_number_of_backtracks_in_ls() const;
  void set_max_number_of_backtracks_in_ls(::google::protobuf::int64 value);

  // optional int32 max_number_of_conflicts_for_quick_check = 16 [default = 10];
  bool has_max_number_of_conflicts_for_quick_check() const;
  void clear_max_number_of_conflicts_for_quick_check();
  static const int kMaxNumberOfConflictsForQuickCheckFieldNumber = 16;
  ::google::protobuf::int32 max_number_of_conflicts_for_quick_check() const;
  void set_max_number_of_conflicts_for_quick_check(::google::protobuf::int32 value);

  // optional int32 max_number_of_conflicts_in_random_solution_generation = 20 [default = 500];
  bool has_max_number_of_conflicts_in_random_solution_generation() const;
  void clear_max_number_of_conflicts_in_random_solution_generation();
  static const int kMaxNumberOfConflictsInRandomSolutionGenerationFieldNumber = 20;
  ::google::protobuf::int32 max_number_of_conflicts_in_random_solution_generation() const;
  void set_max_number_of_conflicts_in_random_solution_generation(::google::protobuf::int32 value);

  // optional int64 max_number_of_explored_assignments_per_try_in_ls = 21 [default = 10000];
  bool has_max_number_of_explored_assignments_per_try_in_ls() const;
  void clear_max_number_of_explored_assignments_per_try_in_ls();
  static const int kMaxNumberOfExploredAssignmentsPerTryInLsFieldNumber = 21;
  ::google::protobuf::int64 max_number_of_explored_assignments_per_try_in_ls() const;
  void set_max_number_of_explored_assignments_per_try_in_ls(::google::protobuf::int64 value);

  // optional bool use_transposition_table_in_ls = 22 [default = true];
  bool has_use_transposition_table_in_ls() const;
  void clear_use_transposition_table_in_ls();
  static const int kUseTranspositionTableInLsFieldNumber = 22;
  bool use_transposition_table_in_ls() const;
  void set_use_transposition_table_in_ls(bool value);

  // optional bool use_learned_binary_clauses_in_lp = 23 [default = true];
  bool has_use_learned_binary_clauses_in_lp() const;
  void clear_use_learned_binary_clauses_in_lp();
  static const int kUseLearnedBinaryClausesInLpFieldNumber = 23;
  bool use_learned_binary_clauses_in_lp() const;
  void set_use_learned_binary_clauses_in_lp(bool value);

  // optional int32 number_of_solvers = 24 [default = 1];
  bool has_number_of_solvers() const;
  void clear_number_of_solvers();
  static const int kNumberOfSolversFieldNumber = 24;
  ::google::protobuf::int32 number_of_solvers() const;
  void set_number_of_solvers(::google::protobuf::int32 value);

  // optional double max_deterministic_time = 27 [default = inf];
  bool has_max_deterministic_time() const;
  void clear_max_deterministic_time();
  static const int kMaxDeterministicTimeFieldNumber = 27;
  double max_deterministic_time() const;
  void set_max_deterministic_time(double value);

  // optional double relative_gap_limit = 28 [default = 0.0001];
  bool has_relative_gap_limit() const;
  void clear_relative_gap_limit();
  static const int kRelativeGapLimitFieldNumber = 28;
  double relative_gap_limit() const;
  void set_relative_gap_limit(double value);

  // optional int32 decomposer_num_variables_threshold = 30 [default = 50];
  bool has_decomposer_num_variables_threshold() const;
  void clear_decomposer_num_variables_threshold();
  static const int kDecomposerNumVariablesThresholdFieldNumber = 30;
  ::google::protobuf::int32 decomposer_num_variables_threshold() const;
  void set_decomposer_num_variables_threshold(::google::protobuf::int32 value);

  // optional int32 num_bop_solvers_used_by_decomposition = 31 [default = 1];
  bool has_num_bop_solvers_used_by_decomposition() const;
  void clear_num_bop_solvers_used_by_decomposition();
  static const int kNumBopSolversUsedByDecompositionFieldNumber = 31;
  ::google::protobuf::int32 num_bop_solvers_used_by_decomposition() const;
  void set_num_bop_solvers_used_by_decomposition(::google::protobuf::int32 value);

  // optional int32 guided_sat_conflicts_chunk = 34 [default = 1000];
  bool has_guided_sat_conflicts_chunk() const;
  void clear_guided_sat_conflicts_chunk();
  static const int kGuidedSatConflictsChunkFieldNumber = 34;
  ::google::protobuf::int32 guided_sat_conflicts_chunk() const;
  void set_guided_sat_conflicts_chunk(::google::protobuf::int32 value);

  // optional int32 max_num_broken_constraints_in_ls = 38 [default = 2147483647];
  bool has_max_num_broken_constraints_in_ls() const;
  void clear_max_num_broken_constraints_in_ls();
  static const int kMaxNumBrokenConstraintsInLsFieldNumber = 38;
  ::google::protobuf::int32 max_num_broken_constraints_in_ls() const;
  void set_max_num_broken_constraints_in_ls(::google::protobuf::int32 value);

  // optional double lp_max_deterministic_time = 37 [default = 1];
  bool has_lp_max_deterministic_time() const;
  void clear_lp_max_deterministic_time();
  static const int kLpMaxDeterministicTimeFieldNumber = 37;
  double lp_max_deterministic_time() const;
  void set_lp_max_deterministic_time(double value);

  // @@protoc_insertion_point(class_scope:operations_research.bop.BopParameters)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<2> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopSolverOptimizerSet > solver_optimizer_sets_;
  public:
  static ::google::protobuf::internal::ExplicitlyConstructed<::std::string> _i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_;
  private:
  ::google::protobuf::internal::ArenaStringPtr default_solver_optimizer_sets_;
  bool log_search_progress_;
  bool prune_search_tree_;
  bool sort_constraints_by_num_terms_;
  bool use_symmetry_;
  int synchronization_type_;
  ::google::protobuf::int32 max_number_of_consecutive_failing_optimizer_calls_;
  bool exploit_symmetry_in_sat_first_solution_;
  bool use_potential_one_flip_repairs_in_ls_;
  bool use_lp_strong_branching_;
  double decomposed_problem_min_time_in_seconds_;
  ::google::protobuf::int32 max_lp_solve_for_feasibility_problems_;
  double max_time_in_seconds_;
  ::google::protobuf::int32 max_num_decisions_in_ls_;
  ::google::protobuf::int32 random_seed_;
  ::google::protobuf::int32 num_relaxed_vars_;
  ::google::protobuf::int32 max_number_of_conflicts_in_random_lns_;
  bool compute_estimated_impact_;
  bool use_random_lns_;
  bool use_lp_lns_;
  bool use_sat_to_choose_lns_neighbourhood_;
  ::google::protobuf::int32 num_random_lns_tries_;
  ::google::protobuf::int64 max_number_of_backtracks_in_ls_;
  ::google::protobuf::int32 max_number_of_conflicts_for_quick_check_;
  ::google::protobuf::int32 max_number_of_conflicts_in_random_solution_generation_;
  ::google::protobuf::int64 max_number_of_explored_assignments_per_try_in_ls_;
  bool use_transposition_table_in_ls_;
  bool use_learned_binary_clauses_in_lp_;
  ::google::protobuf::int32 number_of_solvers_;
  double max_deterministic_time_;
  double relative_gap_limit_;
  ::google::protobuf::int32 decomposer_num_variables_threshold_;
  ::google::protobuf::int32 num_bop_solvers_used_by_decomposition_;
  ::google::protobuf::int32 guided_sat_conflicts_chunk_;
  ::google::protobuf::int32 max_num_broken_constraints_in_ls_;
  double lp_max_deterministic_time_;
  friend struct ::TableStruct_ortools_2fbop_2fbop_5fparameters_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BopOptimizerMethod

// optional .operations_research.bop.BopOptimizerMethod.OptimizerType type = 1;
inline bool BopOptimizerMethod::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BopOptimizerMethod::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::operations_research::bop::BopOptimizerMethod_OptimizerType BopOptimizerMethod::type() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopOptimizerMethod.type)
  return static_cast< ::operations_research::bop::BopOptimizerMethod_OptimizerType >(type_);
}
inline void BopOptimizerMethod::set_type(::operations_research::bop::BopOptimizerMethod_OptimizerType value) {
  assert(::operations_research::bop::BopOptimizerMethod_OptimizerType_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  type_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopOptimizerMethod.type)
}

// -------------------------------------------------------------------

// BopSolverOptimizerSet

// repeated .operations_research.bop.BopOptimizerMethod methods = 1;
inline int BopSolverOptimizerSet::methods_size() const {
  return methods_.size();
}
inline void BopSolverOptimizerSet::clear_methods() {
  methods_.Clear();
}
inline ::operations_research::bop::BopOptimizerMethod* BopSolverOptimizerSet::mutable_methods(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.bop.BopSolverOptimizerSet.methods)
  return methods_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopOptimizerMethod >*
BopSolverOptimizerSet::mutable_methods() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.bop.BopSolverOptimizerSet.methods)
  return &methods_;
}
inline const ::operations_research::bop::BopOptimizerMethod& BopSolverOptimizerSet::methods(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopSolverOptimizerSet.methods)
  return methods_.Get(index);
}
inline ::operations_research::bop::BopOptimizerMethod* BopSolverOptimizerSet::add_methods() {
  // @@protoc_insertion_point(field_add:operations_research.bop.BopSolverOptimizerSet.methods)
  return methods_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopOptimizerMethod >&
BopSolverOptimizerSet::methods() const {
  // @@protoc_insertion_point(field_list:operations_research.bop.BopSolverOptimizerSet.methods)
  return methods_;
}

// -------------------------------------------------------------------

// BopParameters

// optional double max_time_in_seconds = 1 [default = inf];
inline bool BopParameters::has_max_time_in_seconds() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void BopParameters::clear_max_time_in_seconds() {
  max_time_in_seconds_ = std::numeric_limits<double>::infinity();
  _has_bits_[0] &= ~0x00001000u;
}
inline double BopParameters::max_time_in_seconds() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_time_in_seconds)
  return max_time_in_seconds_;
}
inline void BopParameters::set_max_time_in_seconds(double value) {
  _has_bits_[0] |= 0x00001000u;
  max_time_in_seconds_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_time_in_seconds)
}

// optional double max_deterministic_time = 27 [default = inf];
inline bool BopParameters::has_max_deterministic_time() const {
  return (_has_bits_[0] & 0x20000000u) != 0;
}
inline void BopParameters::clear_max_deterministic_time() {
  max_deterministic_time_ = std::numeric_limits<double>::infinity();
  _has_bits_[0] &= ~0x20000000u;
}
inline double BopParameters::max_deterministic_time() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_deterministic_time)
  return max_deterministic_time_;
}
inline void BopParameters::set_max_deterministic_time(double value) {
  _has_bits_[0] |= 0x20000000u;
  max_deterministic_time_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_deterministic_time)
}

// optional double lp_max_deterministic_time = 37 [default = 1];
inline bool BopParameters::has_lp_max_deterministic_time() const {
  return (_has_bits_[1] & 0x00000008u) != 0;
}
inline void BopParameters::clear_lp_max_deterministic_time() {
  lp_max_deterministic_time_ = 1;
  _has_bits_[1] &= ~0x00000008u;
}
inline double BopParameters::lp_max_deterministic_time() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.lp_max_deterministic_time)
  return lp_max_deterministic_time_;
}
inline void BopParameters::set_lp_max_deterministic_time(double value) {
  _has_bits_[1] |= 0x00000008u;
  lp_max_deterministic_time_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.lp_max_deterministic_time)
}

// optional int32 max_number_of_consecutive_failing_optimizer_calls = 35;
inline bool BopParameters::has_max_number_of_consecutive_failing_optimizer_calls() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void BopParameters::clear_max_number_of_consecutive_failing_optimizer_calls() {
  max_number_of_consecutive_failing_optimizer_calls_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::google::protobuf::int32 BopParameters::max_number_of_consecutive_failing_optimizer_calls() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_number_of_consecutive_failing_optimizer_calls)
  return max_number_of_consecutive_failing_optimizer_calls_;
}
inline void BopParameters::set_max_number_of_consecutive_failing_optimizer_calls(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000040u;
  max_number_of_consecutive_failing_optimizer_calls_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_number_of_consecutive_failing_optimizer_calls)
}

// optional double relative_gap_limit = 28 [default = 0.0001];
inline bool BopParameters::has_relative_gap_limit() const {
  return (_has_bits_[0] & 0x40000000u) != 0;
}
inline void BopParameters::clear_relative_gap_limit() {
  relative_gap_limit_ = 0.0001;
  _has_bits_[0] &= ~0x40000000u;
}
inline double BopParameters::relative_gap_limit() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.relative_gap_limit)
  return relative_gap_limit_;
}
inline void BopParameters::set_relative_gap_limit(double value) {
  _has_bits_[0] |= 0x40000000u;
  relative_gap_limit_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.relative_gap_limit)
}

// optional int32 max_num_decisions_in_ls = 2 [default = 4];
inline bool BopParameters::has_max_num_decisions_in_ls() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void BopParameters::clear_max_num_decisions_in_ls() {
  max_num_decisions_in_ls_ = 4;
  _has_bits_[0] &= ~0x00002000u;
}
inline ::google::protobuf::int32 BopParameters::max_num_decisions_in_ls() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_num_decisions_in_ls)
  return max_num_decisions_in_ls_;
}
inline void BopParameters::set_max_num_decisions_in_ls(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00002000u;
  max_num_decisions_in_ls_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_num_decisions_in_ls)
}

// optional int32 max_num_broken_constraints_in_ls = 38 [default = 2147483647];
inline bool BopParameters::has_max_num_broken_constraints_in_ls() const {
  return (_has_bits_[1] & 0x00000004u) != 0;
}
inline void BopParameters::clear_max_num_broken_constraints_in_ls() {
  max_num_broken_constraints_in_ls_ = 2147483647;
  _has_bits_[1] &= ~0x00000004u;
}
inline ::google::protobuf::int32 BopParameters::max_num_broken_constraints_in_ls() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_num_broken_constraints_in_ls)
  return max_num_broken_constraints_in_ls_;
}
inline void BopParameters::set_max_num_broken_constraints_in_ls(::google::protobuf::int32 value) {
  _has_bits_[1] |= 0x00000004u;
  max_num_broken_constraints_in_ls_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_num_broken_constraints_in_ls)
}

// optional bool log_search_progress = 14 [default = false];
inline bool BopParameters::has_log_search_progress() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BopParameters::clear_log_search_progress() {
  log_search_progress_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool BopParameters::log_search_progress() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.log_search_progress)
  return log_search_progress_;
}
inline void BopParameters::set_log_search_progress(bool value) {
  _has_bits_[0] |= 0x00000002u;
  log_search_progress_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.log_search_progress)
}

// optional bool compute_estimated_impact = 3 [default = true];
inline bool BopParameters::has_compute_estimated_impact() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void BopParameters::clear_compute_estimated_impact() {
  compute_estimated_impact_ = true;
  _has_bits_[0] &= ~0x00020000u;
}
inline bool BopParameters::compute_estimated_impact() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.compute_estimated_impact)
  return compute_estimated_impact_;
}
inline void BopParameters::set_compute_estimated_impact(bool value) {
  _has_bits_[0] |= 0x00020000u;
  compute_estimated_impact_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.compute_estimated_impact)
}

// optional bool prune_search_tree = 4 [default = false];
inline bool BopParameters::has_prune_search_tree() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BopParameters::clear_prune_search_tree() {
  prune_search_tree_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool BopParameters::prune_search_tree() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.prune_search_tree)
  return prune_search_tree_;
}
inline void BopParameters::set_prune_search_tree(bool value) {
  _has_bits_[0] |= 0x00000004u;
  prune_search_tree_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.prune_search_tree)
}

// optional bool sort_constraints_by_num_terms = 5 [default = false];
inline bool BopParameters::has_sort_constraints_by_num_terms() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BopParameters::clear_sort_constraints_by_num_terms() {
  sort_constraints_by_num_terms_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool BopParameters::sort_constraints_by_num_terms() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.sort_constraints_by_num_terms)
  return sort_constraints_by_num_terms_;
}
inline void BopParameters::set_sort_constraints_by_num_terms(bool value) {
  _has_bits_[0] |= 0x00000008u;
  sort_constraints_by_num_terms_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.sort_constraints_by_num_terms)
}

// optional bool use_random_lns = 6 [default = true];
inline bool BopParameters::has_use_random_lns() const {
  return (_has_bits_[0] & 0x00040000u) != 0;
}
inline void BopParameters::clear_use_random_lns() {
  use_random_lns_ = true;
  _has_bits_[0] &= ~0x00040000u;
}
inline bool BopParameters::use_random_lns() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.use_random_lns)
  return use_random_lns_;
}
inline void BopParameters::set_use_random_lns(bool value) {
  _has_bits_[0] |= 0x00040000u;
  use_random_lns_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.use_random_lns)
}

// optional int32 random_seed = 7 [default = 8];
inline bool BopParameters::has_random_seed() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void BopParameters::clear_random_seed() {
  random_seed_ = 8;
  _has_bits_[0] &= ~0x00004000u;
}
inline ::google::protobuf::int32 BopParameters::random_seed() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.random_seed)
  return random_seed_;
}
inline void BopParameters::set_random_seed(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00004000u;
  random_seed_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.random_seed)
}

// optional int32 num_relaxed_vars = 8 [default = 10];
inline bool BopParameters::has_num_relaxed_vars() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void BopParameters::clear_num_relaxed_vars() {
  num_relaxed_vars_ = 10;
  _has_bits_[0] &= ~0x00008000u;
}
inline ::google::protobuf::int32 BopParameters::num_relaxed_vars() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.num_relaxed_vars)
  return num_relaxed_vars_;
}
inline void BopParameters::set_num_relaxed_vars(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00008000u;
  num_relaxed_vars_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.num_relaxed_vars)
}

// optional int32 max_number_of_conflicts_in_random_lns = 9 [default = 2500];
inline bool BopParameters::has_max_number_of_conflicts_in_random_lns() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void BopParameters::clear_max_number_of_conflicts_in_random_lns() {
  max_number_of_conflicts_in_random_lns_ = 2500;
  _has_bits_[0] &= ~0x00010000u;
}
inline ::google::protobuf::int32 BopParameters::max_number_of_conflicts_in_random_lns() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_number_of_conflicts_in_random_lns)
  return max_number_of_conflicts_in_random_lns_;
}
inline void BopParameters::set_max_number_of_conflicts_in_random_lns(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00010000u;
  max_number_of_conflicts_in_random_lns_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_number_of_conflicts_in_random_lns)
}

// optional int32 num_random_lns_tries = 10 [default = 1];
inline bool BopParameters::has_num_random_lns_tries() const {
  return (_has_bits_[0] & 0x00200000u) != 0;
}
inline void BopParameters::clear_num_random_lns_tries() {
  num_random_lns_tries_ = 1;
  _has_bits_[0] &= ~0x00200000u;
}
inline ::google::protobuf::int32 BopParameters::num_random_lns_tries() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.num_random_lns_tries)
  return num_random_lns_tries_;
}
inline void BopParameters::set_num_random_lns_tries(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00200000u;
  num_random_lns_tries_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.num_random_lns_tries)
}

// optional int64 max_number_of_backtracks_in_ls = 11 [default = 100000000];
inline bool BopParameters::has_max_number_of_backtracks_in_ls() const {
  return (_has_bits_[0] & 0x00400000u) != 0;
}
inline void BopParameters::clear_max_number_of_backtracks_in_ls() {
  max_number_of_backtracks_in_ls_ = PROTOBUF_LONGLONG(100000000);
  _has_bits_[0] &= ~0x00400000u;
}
inline ::google::protobuf::int64 BopParameters::max_number_of_backtracks_in_ls() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_number_of_backtracks_in_ls)
  return max_number_of_backtracks_in_ls_;
}
inline void BopParameters::set_max_number_of_backtracks_in_ls(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00400000u;
  max_number_of_backtracks_in_ls_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_number_of_backtracks_in_ls)
}

// optional bool use_lp_lns = 12 [default = true];
inline bool BopParameters::has_use_lp_lns() const {
  return (_has_bits_[0] & 0x00080000u) != 0;
}
inline void BopParameters::clear_use_lp_lns() {
  use_lp_lns_ = true;
  _has_bits_[0] &= ~0x00080000u;
}
inline bool BopParameters::use_lp_lns() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.use_lp_lns)
  return use_lp_lns_;
}
inline void BopParameters::set_use_lp_lns(bool value) {
  _has_bits_[0] |= 0x00080000u;
  use_lp_lns_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.use_lp_lns)
}

// optional bool use_sat_to_choose_lns_neighbourhood = 15 [default = true];
inline bool BopParameters::has_use_sat_to_choose_lns_neighbourhood() const {
  return (_has_bits_[0] & 0x00100000u) != 0;
}
inline void BopParameters::clear_use_sat_to_choose_lns_neighbourhood() {
  use_sat_to_choose_lns_neighbourhood_ = true;
  _has_bits_[0] &= ~0x00100000u;
}
inline bool BopParameters::use_sat_to_choose_lns_neighbourhood() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.use_sat_to_choose_lns_neighbourhood)
  return use_sat_to_choose_lns_neighbourhood_;
}
inline void BopParameters::set_use_sat_to_choose_lns_neighbourhood(bool value) {
  _has_bits_[0] |= 0x00100000u;
  use_sat_to_choose_lns_neighbourhood_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.use_sat_to_choose_lns_neighbourhood)
}

// optional int32 max_number_of_conflicts_for_quick_check = 16 [default = 10];
inline bool BopParameters::has_max_number_of_conflicts_for_quick_check() const {
  return (_has_bits_[0] & 0x00800000u) != 0;
}
inline void BopParameters::clear_max_number_of_conflicts_for_quick_check() {
  max_number_of_conflicts_for_quick_check_ = 10;
  _has_bits_[0] &= ~0x00800000u;
}
inline ::google::protobuf::int32 BopParameters::max_number_of_conflicts_for_quick_check() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_number_of_conflicts_for_quick_check)
  return max_number_of_conflicts_for_quick_check_;
}
inline void BopParameters::set_max_number_of_conflicts_for_quick_check(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00800000u;
  max_number_of_conflicts_for_quick_check_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_number_of_conflicts_for_quick_check)
}

// optional bool use_symmetry = 17 [default = false];
inline bool BopParameters::has_use_symmetry() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BopParameters::clear_use_symmetry() {
  use_symmetry_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool BopParameters::use_symmetry() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.use_symmetry)
  return use_symmetry_;
}
inline void BopParameters::set_use_symmetry(bool value) {
  _has_bits_[0] |= 0x00000010u;
  use_symmetry_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.use_symmetry)
}

// optional bool exploit_symmetry_in_sat_first_solution = 40 [default = false];
inline bool BopParameters::has_exploit_symmetry_in_sat_first_solution() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void BopParameters::clear_exploit_symmetry_in_sat_first_solution() {
  exploit_symmetry_in_sat_first_solution_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool BopParameters::exploit_symmetry_in_sat_first_solution() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.exploit_symmetry_in_sat_first_solution)
  return exploit_symmetry_in_sat_first_solution_;
}
inline void BopParameters::set_exploit_symmetry_in_sat_first_solution(bool value) {
  _has_bits_[0] |= 0x00000080u;
  exploit_symmetry_in_sat_first_solution_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.exploit_symmetry_in_sat_first_solution)
}

// optional int32 max_number_of_conflicts_in_random_solution_generation = 20 [default = 500];
inline bool BopParameters::has_max_number_of_conflicts_in_random_solution_generation() const {
  return (_has_bits_[0] & 0x01000000u) != 0;
}
inline void BopParameters::clear_max_number_of_conflicts_in_random_solution_generation() {
  max_number_of_conflicts_in_random_solution_generation_ = 500;
  _has_bits_[0] &= ~0x01000000u;
}
inline ::google::protobuf::int32 BopParameters::max_number_of_conflicts_in_random_solution_generation() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_number_of_conflicts_in_random_solution_generation)
  return max_number_of_conflicts_in_random_solution_generation_;
}
inline void BopParameters::set_max_number_of_conflicts_in_random_solution_generation(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x01000000u;
  max_number_of_conflicts_in_random_solution_generation_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_number_of_conflicts_in_random_solution_generation)
}

// optional int64 max_number_of_explored_assignments_per_try_in_ls = 21 [default = 10000];
inline bool BopParameters::has_max_number_of_explored_assignments_per_try_in_ls() const {
  return (_has_bits_[0] & 0x02000000u) != 0;
}
inline void BopParameters::clear_max_number_of_explored_assignments_per_try_in_ls() {
  max_number_of_explored_assignments_per_try_in_ls_ = PROTOBUF_LONGLONG(10000);
  _has_bits_[0] &= ~0x02000000u;
}
inline ::google::protobuf::int64 BopParameters::max_number_of_explored_assignments_per_try_in_ls() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_number_of_explored_assignments_per_try_in_ls)
  return max_number_of_explored_assignments_per_try_in_ls_;
}
inline void BopParameters::set_max_number_of_explored_assignments_per_try_in_ls(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x02000000u;
  max_number_of_explored_assignments_per_try_in_ls_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_number_of_explored_assignments_per_try_in_ls)
}

// optional bool use_transposition_table_in_ls = 22 [default = true];
inline bool BopParameters::has_use_transposition_table_in_ls() const {
  return (_has_bits_[0] & 0x04000000u) != 0;
}
inline void BopParameters::clear_use_transposition_table_in_ls() {
  use_transposition_table_in_ls_ = true;
  _has_bits_[0] &= ~0x04000000u;
}
inline bool BopParameters::use_transposition_table_in_ls() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.use_transposition_table_in_ls)
  return use_transposition_table_in_ls_;
}
inline void BopParameters::set_use_transposition_table_in_ls(bool value) {
  _has_bits_[0] |= 0x04000000u;
  use_transposition_table_in_ls_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.use_transposition_table_in_ls)
}

// optional bool use_potential_one_flip_repairs_in_ls = 39 [default = false];
inline bool BopParameters::has_use_potential_one_flip_repairs_in_ls() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void BopParameters::clear_use_potential_one_flip_repairs_in_ls() {
  use_potential_one_flip_repairs_in_ls_ = false;
  _has_bits_[0] &= ~0x00000100u;
}
inline bool BopParameters::use_potential_one_flip_repairs_in_ls() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.use_potential_one_flip_repairs_in_ls)
  return use_potential_one_flip_repairs_in_ls_;
}
inline void BopParameters::set_use_potential_one_flip_repairs_in_ls(bool value) {
  _has_bits_[0] |= 0x00000100u;
  use_potential_one_flip_repairs_in_ls_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.use_potential_one_flip_repairs_in_ls)
}

// optional bool use_learned_binary_clauses_in_lp = 23 [default = true];
inline bool BopParameters::has_use_learned_binary_clauses_in_lp() const {
  return (_has_bits_[0] & 0x08000000u) != 0;
}
inline void BopParameters::clear_use_learned_binary_clauses_in_lp() {
  use_learned_binary_clauses_in_lp_ = true;
  _has_bits_[0] &= ~0x08000000u;
}
inline bool BopParameters::use_learned_binary_clauses_in_lp() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.use_learned_binary_clauses_in_lp)
  return use_learned_binary_clauses_in_lp_;
}
inline void BopParameters::set_use_learned_binary_clauses_in_lp(bool value) {
  _has_bits_[0] |= 0x08000000u;
  use_learned_binary_clauses_in_lp_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.use_learned_binary_clauses_in_lp)
}

// optional int32 number_of_solvers = 24 [default = 1];
inline bool BopParameters::has_number_of_solvers() const {
  return (_has_bits_[0] & 0x10000000u) != 0;
}
inline void BopParameters::clear_number_of_solvers() {
  number_of_solvers_ = 1;
  _has_bits_[0] &= ~0x10000000u;
}
inline ::google::protobuf::int32 BopParameters::number_of_solvers() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.number_of_solvers)
  return number_of_solvers_;
}
inline void BopParameters::set_number_of_solvers(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x10000000u;
  number_of_solvers_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.number_of_solvers)
}

// optional .operations_research.bop.BopParameters.ThreadSynchronizationType synchronization_type = 25 [default = NO_SYNCHRONIZATION];
inline bool BopParameters::has_synchronization_type() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BopParameters::clear_synchronization_type() {
  synchronization_type_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::operations_research::bop::BopParameters_ThreadSynchronizationType BopParameters::synchronization_type() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.synchronization_type)
  return static_cast< ::operations_research::bop::BopParameters_ThreadSynchronizationType >(synchronization_type_);
}
inline void BopParameters::set_synchronization_type(::operations_research::bop::BopParameters_ThreadSynchronizationType value) {
  assert(::operations_research::bop::BopParameters_ThreadSynchronizationType_IsValid(value));
  _has_bits_[0] |= 0x00000020u;
  synchronization_type_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.synchronization_type)
}

// repeated .operations_research.bop.BopSolverOptimizerSet solver_optimizer_sets = 26;
inline int BopParameters::solver_optimizer_sets_size() const {
  return solver_optimizer_sets_.size();
}
inline void BopParameters::clear_solver_optimizer_sets() {
  solver_optimizer_sets_.Clear();
}
inline ::operations_research::bop::BopSolverOptimizerSet* BopParameters::mutable_solver_optimizer_sets(int index) {
  // @@protoc_insertion_point(field_mutable:operations_research.bop.BopParameters.solver_optimizer_sets)
  return solver_optimizer_sets_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopSolverOptimizerSet >*
BopParameters::mutable_solver_optimizer_sets() {
  // @@protoc_insertion_point(field_mutable_list:operations_research.bop.BopParameters.solver_optimizer_sets)
  return &solver_optimizer_sets_;
}
inline const ::operations_research::bop::BopSolverOptimizerSet& BopParameters::solver_optimizer_sets(int index) const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.solver_optimizer_sets)
  return solver_optimizer_sets_.Get(index);
}
inline ::operations_research::bop::BopSolverOptimizerSet* BopParameters::add_solver_optimizer_sets() {
  // @@protoc_insertion_point(field_add:operations_research.bop.BopParameters.solver_optimizer_sets)
  return solver_optimizer_sets_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::operations_research::bop::BopSolverOptimizerSet >&
BopParameters::solver_optimizer_sets() const {
  // @@protoc_insertion_point(field_list:operations_research.bop.BopParameters.solver_optimizer_sets)
  return solver_optimizer_sets_;
}

// optional string default_solver_optimizer_sets = 33 [default = "methods:{type:LOCAL_SEARCH }                       methods:{type:RANDOM_FIRST_SOLUTION }              methods:{type:LINEAR_RELAXATION }                  methods:{type:LP_FIRST_SOLUTION }                  methods:{type:OBJECTIVE_FIRST_SOLUTION }           methods:{type:USER_GUIDED_FIRST_SOLUTION }         methods:{type:RANDOM_CONSTRAINT_LNS_GUIDED_BY_LP } methods:{type:RANDOM_VARIABLE_LNS_GUIDED_BY_LP }   methods:{type:RELATION_GRAPH_LNS }                 methods:{type:RELATION_GRAPH_LNS_GUIDED_BY_LP }    methods:{type:RANDOM_CONSTRAINT_LNS }              methods:{type:RANDOM_VARIABLE_LNS }                methods:{type:SAT_CORE_BASED }                     methods:{type:COMPLETE_LNS }                       "];
inline bool BopParameters::has_default_solver_optimizer_sets() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BopParameters::clear_default_solver_optimizer_sets() {
  default_solver_optimizer_sets_.ClearToDefaultNoArena(&::operations_research::bop::BopParameters::_i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_.get());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& BopParameters::default_solver_optimizer_sets() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.default_solver_optimizer_sets)
  return default_solver_optimizer_sets_.GetNoArena();
}
inline void BopParameters::set_default_solver_optimizer_sets(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  default_solver_optimizer_sets_.SetNoArena(&::operations_research::bop::BopParameters::_i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_.get(), value);
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.default_solver_optimizer_sets)
}
#if LANG_CXX11
inline void BopParameters::set_default_solver_optimizer_sets(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  default_solver_optimizer_sets_.SetNoArena(
    &::operations_research::bop::BopParameters::_i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:operations_research.bop.BopParameters.default_solver_optimizer_sets)
}
#endif
inline void BopParameters::set_default_solver_optimizer_sets(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  default_solver_optimizer_sets_.SetNoArena(&::operations_research::bop::BopParameters::_i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:operations_research.bop.BopParameters.default_solver_optimizer_sets)
}
inline void BopParameters::set_default_solver_optimizer_sets(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  default_solver_optimizer_sets_.SetNoArena(&::operations_research::bop::BopParameters::_i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:operations_research.bop.BopParameters.default_solver_optimizer_sets)
}
inline ::std::string* BopParameters::mutable_default_solver_optimizer_sets() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:operations_research.bop.BopParameters.default_solver_optimizer_sets)
  return default_solver_optimizer_sets_.MutableNoArena(&::operations_research::bop::BopParameters::_i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_.get());
}
inline ::std::string* BopParameters::release_default_solver_optimizer_sets() {
  // @@protoc_insertion_point(field_release:operations_research.bop.BopParameters.default_solver_optimizer_sets)
  if (!has_default_solver_optimizer_sets()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return default_solver_optimizer_sets_.ReleaseNonDefaultNoArena(&::operations_research::bop::BopParameters::_i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_.get());
}
inline void BopParameters::set_allocated_default_solver_optimizer_sets(::std::string* default_solver_optimizer_sets) {
  if (default_solver_optimizer_sets != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  default_solver_optimizer_sets_.SetAllocatedNoArena(&::operations_research::bop::BopParameters::_i_give_permission_to_break_this_code_default_default_solver_optimizer_sets_.get(), default_solver_optimizer_sets);
  // @@protoc_insertion_point(field_set_allocated:operations_research.bop.BopParameters.default_solver_optimizer_sets)
}

// optional bool use_lp_strong_branching = 29 [default = false];
inline bool BopParameters::has_use_lp_strong_branching() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void BopParameters::clear_use_lp_strong_branching() {
  use_lp_strong_branching_ = false;
  _has_bits_[0] &= ~0x00000200u;
}
inline bool BopParameters::use_lp_strong_branching() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.use_lp_strong_branching)
  return use_lp_strong_branching_;
}
inline void BopParameters::set_use_lp_strong_branching(bool value) {
  _has_bits_[0] |= 0x00000200u;
  use_lp_strong_branching_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.use_lp_strong_branching)
}

// optional int32 decomposer_num_variables_threshold = 30 [default = 50];
inline bool BopParameters::has_decomposer_num_variables_threshold() const {
  return (_has_bits_[0] & 0x80000000u) != 0;
}
inline void BopParameters::clear_decomposer_num_variables_threshold() {
  decomposer_num_variables_threshold_ = 50;
  _has_bits_[0] &= ~0x80000000u;
}
inline ::google::protobuf::int32 BopParameters::decomposer_num_variables_threshold() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.decomposer_num_variables_threshold)
  return decomposer_num_variables_threshold_;
}
inline void BopParameters::set_decomposer_num_variables_threshold(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x80000000u;
  decomposer_num_variables_threshold_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.decomposer_num_variables_threshold)
}

// optional int32 num_bop_solvers_used_by_decomposition = 31 [default = 1];
inline bool BopParameters::has_num_bop_solvers_used_by_decomposition() const {
  return (_has_bits_[1] & 0x00000001u) != 0;
}
inline void BopParameters::clear_num_bop_solvers_used_by_decomposition() {
  num_bop_solvers_used_by_decomposition_ = 1;
  _has_bits_[1] &= ~0x00000001u;
}
inline ::google::protobuf::int32 BopParameters::num_bop_solvers_used_by_decomposition() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.num_bop_solvers_used_by_decomposition)
  return num_bop_solvers_used_by_decomposition_;
}
inline void BopParameters::set_num_bop_solvers_used_by_decomposition(::google::protobuf::int32 value) {
  _has_bits_[1] |= 0x00000001u;
  num_bop_solvers_used_by_decomposition_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.num_bop_solvers_used_by_decomposition)
}

// optional double decomposed_problem_min_time_in_seconds = 36 [default = 0];
inline bool BopParameters::has_decomposed_problem_min_time_in_seconds() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void BopParameters::clear_decomposed_problem_min_time_in_seconds() {
  decomposed_problem_min_time_in_seconds_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline double BopParameters::decomposed_problem_min_time_in_seconds() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.decomposed_problem_min_time_in_seconds)
  return decomposed_problem_min_time_in_seconds_;
}
inline void BopParameters::set_decomposed_problem_min_time_in_seconds(double value) {
  _has_bits_[0] |= 0x00000400u;
  decomposed_problem_min_time_in_seconds_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.decomposed_problem_min_time_in_seconds)
}

// optional int32 guided_sat_conflicts_chunk = 34 [default = 1000];
inline bool BopParameters::has_guided_sat_conflicts_chunk() const {
  return (_has_bits_[1] & 0x00000002u) != 0;
}
inline void BopParameters::clear_guided_sat_conflicts_chunk() {
  guided_sat_conflicts_chunk_ = 1000;
  _has_bits_[1] &= ~0x00000002u;
}
inline ::google::protobuf::int32 BopParameters::guided_sat_conflicts_chunk() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.guided_sat_conflicts_chunk)
  return guided_sat_conflicts_chunk_;
}
inline void BopParameters::set_guided_sat_conflicts_chunk(::google::protobuf::int32 value) {
  _has_bits_[1] |= 0x00000002u;
  guided_sat_conflicts_chunk_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.guided_sat_conflicts_chunk)
}

// optional int32 max_lp_solve_for_feasibility_problems = 41 [default = 0];
inline bool BopParameters::has_max_lp_solve_for_feasibility_problems() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void BopParameters::clear_max_lp_solve_for_feasibility_problems() {
  max_lp_solve_for_feasibility_problems_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::google::protobuf::int32 BopParameters::max_lp_solve_for_feasibility_problems() const {
  // @@protoc_insertion_point(field_get:operations_research.bop.BopParameters.max_lp_solve_for_feasibility_problems)
  return max_lp_solve_for_feasibility_problems_;
}
inline void BopParameters::set_max_lp_solve_for_feasibility_problems(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000800u;
  max_lp_solve_for_feasibility_problems_ = value;
  // @@protoc_insertion_point(field_set:operations_research.bop.BopParameters.max_lp_solve_for_feasibility_problems)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bop
}  // namespace operations_research

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::operations_research::bop::BopOptimizerMethod_OptimizerType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::operations_research::bop::BopOptimizerMethod_OptimizerType>() {
  return ::operations_research::bop::BopOptimizerMethod_OptimizerType_descriptor();
}
template <> struct is_proto_enum< ::operations_research::bop::BopParameters_ThreadSynchronizationType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::operations_research::bop::BopParameters_ThreadSynchronizationType>() {
  return ::operations_research::bop::BopParameters_ThreadSynchronizationType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ortools_2fbop_2fbop_5fparameters_2eproto
